
package de.dat.glassrep.services.vehicleidentificationservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "VehicleIdentificationService", targetNamespace = "http://sphinx.dat.de/services/VehicleIdentificationService", wsdlLocation = "http://www.dat.de/GlassRep/services/VehicleIdentificationService?wsdl")
public class VehicleIdentificationService_Service
    extends Service
{

    private final static URL VEHICLEIDENTIFICATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException VEHICLEIDENTIFICATIONSERVICE_EXCEPTION;
    private final static QName VEHICLEIDENTIFICATIONSERVICE_QNAME = new QName("http://sphinx.dat.de/services/VehicleIdentificationService", "VehicleIdentificationService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://www.dat.de/GlassRep/services/VehicleIdentificationService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VEHICLEIDENTIFICATIONSERVICE_WSDL_LOCATION = url;
        VEHICLEIDENTIFICATIONSERVICE_EXCEPTION = e;
    }

    public VehicleIdentificationService_Service() {
        super(__getWsdlLocation(), VEHICLEIDENTIFICATIONSERVICE_QNAME);
    }

    public VehicleIdentificationService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), VEHICLEIDENTIFICATIONSERVICE_QNAME, features);
    }

    public VehicleIdentificationService_Service(URL wsdlLocation) {
        super(wsdlLocation, VEHICLEIDENTIFICATIONSERVICE_QNAME);
    }

    public VehicleIdentificationService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VEHICLEIDENTIFICATIONSERVICE_QNAME, features);
    }

    public VehicleIdentificationService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VehicleIdentificationService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns VehicleIdentificationService
     */
    @WebEndpoint(name = "VehicleIdentificationServicePort")
    public VehicleIdentificationService getVehicleIdentificationServicePort() {
        return super.getPort(new QName("http://sphinx.dat.de/services/VehicleIdentificationService", "VehicleIdentificationServicePort"), VehicleIdentificationService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VehicleIdentificationService
     */
    @WebEndpoint(name = "VehicleIdentificationServicePort")
    public VehicleIdentificationService getVehicleIdentificationServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://sphinx.dat.de/services/VehicleIdentificationService", "VehicleIdentificationServicePort"), VehicleIdentificationService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VEHICLEIDENTIFICATIONSERVICE_EXCEPTION!= null) {
            throw VEHICLEIDENTIFICATIONSERVICE_EXCEPTION;
        }
        return VEHICLEIDENTIFICATIONSERVICE_WSDL_LOCATION;
    }

}
