
package de.dat.glassrep.services.dmscreatecontract;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DMSCreateContract", targetNamespace = "http://sphinx.dat.de/services/GlassRep", wsdlLocation = "http://www.dat.de/GlassRep/services/DMSCreateContract?wsdl")
public class DMSCreateContract_Service
    extends Service
{

    private final static URL DMSCREATECONTRACT_WSDL_LOCATION;
    private final static WebServiceException DMSCREATECONTRACT_EXCEPTION;
    private final static QName DMSCREATECONTRACT_QNAME = new QName("http://sphinx.dat.de/services/GlassRep", "DMSCreateContract");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://www.dat.de/GlassRep/services/DMSCreateContract?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DMSCREATECONTRACT_WSDL_LOCATION = url;
        DMSCREATECONTRACT_EXCEPTION = e;
    }

    public DMSCreateContract_Service() {
        super(__getWsdlLocation(), DMSCREATECONTRACT_QNAME);
    }

    public DMSCreateContract_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), DMSCREATECONTRACT_QNAME, features);
    }

    public DMSCreateContract_Service(URL wsdlLocation) {
        super(wsdlLocation, DMSCREATECONTRACT_QNAME);
    }

    public DMSCreateContract_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DMSCREATECONTRACT_QNAME, features);
    }

    public DMSCreateContract_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DMSCreateContract_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DMSCreateContract
     */
    @WebEndpoint(name = "DMSCreateContractPortBinding")
    public DMSCreateContract getDMSCreateContractPortBinding() {
        return super.getPort(new QName("http://sphinx.dat.de/services/GlassRep", "DMSCreateContractPortBinding"), DMSCreateContract.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DMSCreateContract
     */
    @WebEndpoint(name = "DMSCreateContractPortBinding")
    public DMSCreateContract getDMSCreateContractPortBinding(WebServiceFeature... features) {
        return super.getPort(new QName("http://sphinx.dat.de/services/GlassRep", "DMSCreateContractPortBinding"), DMSCreateContract.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DMSCREATECONTRACT_EXCEPTION!= null) {
            throw DMSCREATECONTRACT_EXCEPTION;
        }
        return DMSCREATECONTRACT_WSDL_LOCATION;
    }

}
