
package de.dat.glassrep.services.vehicleselectionservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "VehicleSelectionService", targetNamespace = "http://sphinx.dat.de/services/VehicleSelectionService", wsdlLocation = "http://www.dat.de/GlassRep/services/VehicleSelectionService?wsdl")
public class VehicleSelectionService_Service
    extends Service
{

    private final static URL VEHICLESELECTIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException VEHICLESELECTIONSERVICE_EXCEPTION;
    private final static QName VEHICLESELECTIONSERVICE_QNAME = new QName("http://sphinx.dat.de/services/VehicleSelectionService", "VehicleSelectionService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://www.dat.de/GlassRep/services/VehicleSelectionService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VEHICLESELECTIONSERVICE_WSDL_LOCATION = url;
        VEHICLESELECTIONSERVICE_EXCEPTION = e;
    }

    public VehicleSelectionService_Service() {
        super(__getWsdlLocation(), VEHICLESELECTIONSERVICE_QNAME);
    }

    public VehicleSelectionService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), VEHICLESELECTIONSERVICE_QNAME, features);
    }

    public VehicleSelectionService_Service(URL wsdlLocation) {
        super(wsdlLocation, VEHICLESELECTIONSERVICE_QNAME);
    }

    public VehicleSelectionService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VEHICLESELECTIONSERVICE_QNAME, features);
    }

    public VehicleSelectionService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VehicleSelectionService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns VehicleSelectionService
     */
    @WebEndpoint(name = "VehicleSelectionServicePort")
    public VehicleSelectionService getVehicleSelectionServicePort() {
        return super.getPort(new QName("http://sphinx.dat.de/services/VehicleSelectionService", "VehicleSelectionServicePort"), VehicleSelectionService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VehicleSelectionService
     */
    @WebEndpoint(name = "VehicleSelectionServicePort")
    public VehicleSelectionService getVehicleSelectionServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://sphinx.dat.de/services/VehicleSelectionService", "VehicleSelectionServicePort"), VehicleSelectionService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VEHICLESELECTIONSERVICE_EXCEPTION!= null) {
            throw VEHICLESELECTIONSERVICE_EXCEPTION;
        }
        return VEHICLESELECTIONSERVICE_WSDL_LOCATION;
    }

}
