
package de.dat.datecodeselection.services.vehicleimagery;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "VehicleImagery", targetNamespace = "http://sphinx.dat.de/services/VehicleImagery")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface VehicleImagery {


    /**
     * 
     * @param request
     * @return
     *     returns de.dat.datecodeselection.services.vehicleimagery.VehicleImagesNResponse
     */
    @WebMethod(action = "getVehicleImagesN")
    @WebResult(name = "vehicleImagesN", targetNamespace = "")
    @RequestWrapper(localName = "getVehicleImagesN", targetNamespace = "http://sphinx.dat.de/services/VehicleImagery", className = "de.dat.datecodeselection.services.vehicleimagery.GetVehicleImagesN")
    @ResponseWrapper(localName = "getVehicleImagesNResponse", targetNamespace = "http://sphinx.dat.de/services/VehicleImagery", className = "de.dat.datecodeselection.services.vehicleimagery.GetVehicleImagesNResponse")
    @Action(input = "getVehicleImagesN", output = "http://sphinx.dat.de/services/VehicleImagery/VehicleImagery/getVehicleImagesNResponse")
    public VehicleImagesNResponse getVehicleImagesN(
        @WebParam(name = "request", targetNamespace = "")
        VehicleImagesNRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns de.dat.datecodeselection.services.vehicleimagery.VehicleRimImagesResponse
     */
    @WebMethod(action = "getVehicleRimImages")
    @WebResult(name = "vehicleRimImages", targetNamespace = "")
    @RequestWrapper(localName = "getVehicleRimImages", targetNamespace = "http://sphinx.dat.de/services/VehicleImagery", className = "de.dat.datecodeselection.services.vehicleimagery.GetVehicleRimImages")
    @ResponseWrapper(localName = "getVehicleRimImagesResponse", targetNamespace = "http://sphinx.dat.de/services/VehicleImagery", className = "de.dat.datecodeselection.services.vehicleimagery.GetVehicleRimImagesResponse")
    @Action(input = "getVehicleRimImages", output = "http://sphinx.dat.de/services/VehicleImagery/VehicleImagery/getVehicleRimImagesResponse")
    public VehicleRimImagesResponse getVehicleRimImages(
        @WebParam(name = "request", targetNamespace = "")
        VehicleRimImagesRequest request);

}
