
package de.dat.glassrep.services.dmsgetcontracts;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DMSGetContracts", targetNamespace = "http://sphinx.dat.de/services/GlassRep")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DMSGetContracts {


    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod(action = "getNewContractNumbers")
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getNewContractNumbers", targetNamespace = "http://sphinx.dat.de/services/GlassRep", className = "de.dat.glassrep.services.dmsgetcontracts.GetNewContractNumbers")
    @ResponseWrapper(localName = "getNewContractNumbersResponse", targetNamespace = "http://sphinx.dat.de/services/GlassRep", className = "de.dat.glassrep.services.dmsgetcontracts.GetNewContractNumbersResponse")
    @Action(input = "getNewContractNumbers", output = "http://sphinx.dat.de/services/GlassRep/DMSGetContracts/getNewContractNumbersResponse")
    public List<String> getNewContractNumbers();

    /**
     * 
     * @param contractNumber
     * @return
     *     returns de.dat.glassrep.services.dmsgetcontracts.GetContractsResponse
     */
    @WebMethod(action = "getContract")
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getContract", targetNamespace = "http://sphinx.dat.de/services/GlassRep", className = "de.dat.glassrep.services.dmsgetcontracts.GetContract")
    @ResponseWrapper(localName = "getContractResponse", targetNamespace = "http://sphinx.dat.de/services/GlassRep", className = "de.dat.glassrep.services.dmsgetcontracts.GetContractResponse")
    @Action(input = "getContract", output = "http://sphinx.dat.de/services/GlassRep/DMSGetContracts/getContractResponse")
    public GetContractsResponse getContract(
        @WebParam(name = "contractNumber", targetNamespace = "")
        String contractNumber);

    /**
     * 
     * @return
     *     returns de.dat.glassrep.services.dmsgetcontracts.GetContractsResponse
     */
    @WebMethod(action = "getNewContracts")
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getNewContracts", targetNamespace = "http://sphinx.dat.de/services/GlassRep", className = "de.dat.glassrep.services.dmsgetcontracts.GetNewContracts")
    @ResponseWrapper(localName = "getNewContractsResponse", targetNamespace = "http://sphinx.dat.de/services/GlassRep", className = "de.dat.glassrep.services.dmsgetcontracts.GetNewContractsResponse")
    @Action(input = "getNewContracts", output = "http://sphinx.dat.de/services/GlassRep/DMSGetContracts/getNewContractsResponse")
    public GetContractsResponse getNewContracts();

}
