
package de.dat.glassrep.services.dmsgetcontracts;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DMSGetContracts", targetNamespace = "http://sphinx.dat.de/services/GlassRep", wsdlLocation = "http://www.dat.de/GlassRep/services/DMSGetContracts?wsdl")
public class DMSGetContracts_Service
    extends Service
{

    private final static URL DMSGETCONTRACTS_WSDL_LOCATION;
    private final static WebServiceException DMSGETCONTRACTS_EXCEPTION;
    private final static QName DMSGETCONTRACTS_QNAME = new QName("http://sphinx.dat.de/services/GlassRep", "DMSGetContracts");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://www.dat.de/GlassRep/services/DMSGetContracts?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DMSGETCONTRACTS_WSDL_LOCATION = url;
        DMSGETCONTRACTS_EXCEPTION = e;
    }

    public DMSGetContracts_Service() {
        super(__getWsdlLocation(), DMSGETCONTRACTS_QNAME);
    }

    public DMSGetContracts_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), DMSGETCONTRACTS_QNAME, features);
    }

    public DMSGetContracts_Service(URL wsdlLocation) {
        super(wsdlLocation, DMSGETCONTRACTS_QNAME);
    }

    public DMSGetContracts_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DMSGETCONTRACTS_QNAME, features);
    }

    public DMSGetContracts_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DMSGetContracts_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DMSGetContracts
     */
    @WebEndpoint(name = "DMSGetContractsPortBinding")
    public DMSGetContracts getDMSGetContractsPortBinding() {
        return super.getPort(new QName("http://sphinx.dat.de/services/GlassRep", "DMSGetContractsPortBinding"), DMSGetContracts.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DMSGetContracts
     */
    @WebEndpoint(name = "DMSGetContractsPortBinding")
    public DMSGetContracts getDMSGetContractsPortBinding(WebServiceFeature... features) {
        return super.getPort(new QName("http://sphinx.dat.de/services/GlassRep", "DMSGetContractsPortBinding"), DMSGetContracts.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DMSGETCONTRACTS_EXCEPTION!= null) {
            throw DMSGETCONTRACTS_EXCEPTION;
        }
        return DMSGETCONTRACTS_WSDL_LOCATION;
    }

}
