
package de.dat.datecodeselection.services.vehicleselectionservice;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "VehicleSelectionService", targetNamespace = "http://sphinx.dat.de/services/VehicleSelectionService")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface VehicleSelectionService {


    /**
     * 
     * @param request
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "getVersion")
    @WebResult(name = "version", targetNamespace = "")
    @RequestWrapper(localName = "getVersion", targetNamespace = "http://sphinx.dat.de/services/VehicleSelectionService", className = "de.dat.datecodeselection.services.vehicleselectionservice.GetVersion")
    @ResponseWrapper(localName = "getVersionResponse", targetNamespace = "http://sphinx.dat.de/services/VehicleSelectionService", className = "de.dat.datecodeselection.services.vehicleselectionservice.GetVersionResponse")
    @Action(input = "getVersion", output = "http://sphinx.dat.de/services/VehicleSelectionService/VehicleSelectionService/getVersionResponse")
    public String getVersion(
        @WebParam(name = "request", targetNamespace = "")
        AbstractSelectionRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns java.util.List<java.lang.Integer>
     */
    @WebMethod(action = "getPriceFocusConstructionYears")
    @WebResult(name = "priceFocusConstructionYear", targetNamespace = "")
    @RequestWrapper(localName = "getPriceFocusConstructionYears", targetNamespace = "http://sphinx.dat.de/services/VehicleSelectionService", className = "de.dat.datecodeselection.services.vehicleselectionservice.GetPriceFocusConstructionYears")
    @ResponseWrapper(localName = "getPriceFocusConstructionYearsResponse", targetNamespace = "http://sphinx.dat.de/services/VehicleSelectionService", className = "de.dat.datecodeselection.services.vehicleselectionservice.GetPriceFocusConstructionYearsResponse")
    @Action(input = "getPriceFocusConstructionYears", output = "http://sphinx.dat.de/services/VehicleSelectionService/VehicleSelectionService/getPriceFocusConstructionYearsResponse")
    public List<Integer> getPriceFocusConstructionYears(
        @WebParam(name = "request", targetNamespace = "")
        PriceFocusSelectionRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns de.dat.datecodeselection.services.vehicleselectionservice.SubModelByTextSearchSelectionResponse
     */
    @WebMethod(action = "getSubModelsByTextSearch")
    @WebResult(name = "subModelsByTextSearch", targetNamespace = "")
    @RequestWrapper(localName = "getSubModelsByTextSearch", targetNamespace = "http://sphinx.dat.de/services/VehicleSelectionService", className = "de.dat.datecodeselection.services.vehicleselectionservice.GetSubModelsByTextSearch")
    @ResponseWrapper(localName = "getSubModelsByTextSearchResponse", targetNamespace = "http://sphinx.dat.de/services/VehicleSelectionService", className = "de.dat.datecodeselection.services.vehicleselectionservice.GetSubModelsByTextSearchResponse")
    @Action(input = "getSubModelsByTextSearch", output = "http://sphinx.dat.de/services/VehicleSelectionService/VehicleSelectionService/getSubModelsByTextSearchResponse")
    public SubModelByTextSearchSelectionResponse getSubModelsByTextSearch(
        @WebParam(name = "request", targetNamespace = "")
        SubModelByTextSearchSelectionRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns java.util.List<de.dat.datecodeselection.services.vehicleselectionservice.IntegerStringPair>
     */
    @WebMethod(action = "getVehicleTypes")
    @WebResult(name = "vehicleType", targetNamespace = "")
    @RequestWrapper(localName = "getVehicleTypes", targetNamespace = "http://sphinx.dat.de/services/VehicleSelectionService", className = "de.dat.datecodeselection.services.vehicleselectionservice.GetVehicleTypes")
    @ResponseWrapper(localName = "getVehicleTypesResponse", targetNamespace = "http://sphinx.dat.de/services/VehicleSelectionService", className = "de.dat.datecodeselection.services.vehicleselectionservice.GetVehicleTypesResponse")
    @Action(input = "getVehicleTypes", output = "http://sphinx.dat.de/services/VehicleSelectionService/VehicleSelectionService/getVehicleTypesResponse")
    public List<IntegerStringPair> getVehicleTypes(
        @WebParam(name = "request", targetNamespace = "")
        BasicSelectionRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns java.util.List<de.dat.datecodeselection.services.vehicleselectionservice.IntegerStringPair>
     */
    @WebMethod(action = "getManufacturers")
    @WebResult(name = "manufacturer", targetNamespace = "")
    @RequestWrapper(localName = "getManufacturers", targetNamespace = "http://sphinx.dat.de/services/VehicleSelectionService", className = "de.dat.datecodeselection.services.vehicleselectionservice.GetManufacturers")
    @ResponseWrapper(localName = "getManufacturersResponse", targetNamespace = "http://sphinx.dat.de/services/VehicleSelectionService", className = "de.dat.datecodeselection.services.vehicleselectionservice.GetManufacturersResponse")
    @Action(input = "getManufacturers", output = "http://sphinx.dat.de/services/VehicleSelectionService/VehicleSelectionService/getManufacturersResponse")
    public List<IntegerStringPair> getManufacturers(
        @WebParam(name = "request", targetNamespace = "")
        ManufacturerSelectionRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns java.util.List<de.dat.datecodeselection.services.vehicleselectionservice.IntegerStringPair>
     */
    @WebMethod(action = "getBaseModels")
    @WebResult(name = "baseModel", targetNamespace = "")
    @RequestWrapper(localName = "getBaseModels", targetNamespace = "http://sphinx.dat.de/services/VehicleSelectionService", className = "de.dat.datecodeselection.services.vehicleselectionservice.GetBaseModels")
    @ResponseWrapper(localName = "getBaseModelsResponse", targetNamespace = "http://sphinx.dat.de/services/VehicleSelectionService", className = "de.dat.datecodeselection.services.vehicleselectionservice.GetBaseModelsResponse")
    @Action(input = "getBaseModels", output = "http://sphinx.dat.de/services/VehicleSelectionService/VehicleSelectionService/getBaseModelsResponse")
    public List<IntegerStringPair> getBaseModels(
        @WebParam(name = "request", targetNamespace = "")
        BaseModelSelectionRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns java.util.List<de.dat.datecodeselection.services.vehicleselectionservice.BaseModelResult>
     */
    @WebMethod(action = "getBaseModelsN")
    @WebResult(name = "baseModelN", targetNamespace = "")
    @RequestWrapper(localName = "getBaseModelsN", targetNamespace = "http://sphinx.dat.de/services/VehicleSelectionService", className = "de.dat.datecodeselection.services.vehicleselectionservice.GetBaseModelsN")
    @ResponseWrapper(localName = "getBaseModelsNResponse", targetNamespace = "http://sphinx.dat.de/services/VehicleSelectionService", className = "de.dat.datecodeselection.services.vehicleselectionservice.GetBaseModelsNResponse")
    @Action(input = "getBaseModelsN", output = "http://sphinx.dat.de/services/VehicleSelectionService/VehicleSelectionService/getBaseModelsNResponse")
    public List<BaseModelResult> getBaseModelsN(
        @WebParam(name = "request", targetNamespace = "")
        BaseModelSelectionRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns java.util.List<de.dat.datecodeselection.services.vehicleselectionservice.IntegerStringPair>
     */
    @WebMethod(action = "getHgvPlatformTypes")
    @WebResult(name = "hgvPlatformType", targetNamespace = "")
    @RequestWrapper(localName = "getHgvPlatformTypes", targetNamespace = "http://sphinx.dat.de/services/VehicleSelectionService", className = "de.dat.datecodeselection.services.vehicleselectionservice.GetHgvPlatformTypes")
    @ResponseWrapper(localName = "getHgvPlatformTypesResponse", targetNamespace = "http://sphinx.dat.de/services/VehicleSelectionService", className = "de.dat.datecodeselection.services.vehicleselectionservice.GetHgvPlatformTypesResponse")
    @Action(input = "getHgvPlatformTypes", output = "http://sphinx.dat.de/services/VehicleSelectionService/VehicleSelectionService/getHgvPlatformTypesResponse")
    public List<IntegerStringPair> getHgvPlatformTypes(
        @WebParam(name = "request", targetNamespace = "")
        BasicSelectionRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns java.util.List<de.dat.datecodeselection.services.vehicleselectionservice.IntegerStringPair>
     */
    @WebMethod(action = "getHgvPlatformManufacturers")
    @WebResult(name = "hgvPlatformManufacturer", targetNamespace = "")
    @RequestWrapper(localName = "getHgvPlatformManufacturers", targetNamespace = "http://sphinx.dat.de/services/VehicleSelectionService", className = "de.dat.datecodeselection.services.vehicleselectionservice.GetHgvPlatformManufacturers")
    @ResponseWrapper(localName = "getHgvPlatformManufacturersResponse", targetNamespace = "http://sphinx.dat.de/services/VehicleSelectionService", className = "de.dat.datecodeselection.services.vehicleselectionservice.GetHgvPlatformManufacturersResponse")
    @Action(input = "getHgvPlatformManufacturers", output = "http://sphinx.dat.de/services/VehicleSelectionService/VehicleSelectionService/getHgvPlatformManufacturersResponse")
    public List<IntegerStringPair> getHgvPlatformManufacturers(
        @WebParam(name = "request", targetNamespace = "")
        HgvPlatformManufacturerSelectionRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns java.util.List<de.dat.datecodeselection.services.vehicleselectionservice.IntegerStringPair>
     */
    @WebMethod(action = "getHgvPlatformBaseModels")
    @WebResult(name = "hgvPlatformBaseModel", targetNamespace = "")
    @RequestWrapper(localName = "getHgvPlatformBaseModels", targetNamespace = "http://sphinx.dat.de/services/VehicleSelectionService", className = "de.dat.datecodeselection.services.vehicleselectionservice.GetHgvPlatformBaseModels")
    @ResponseWrapper(localName = "getHgvPlatformBaseModelsResponse", targetNamespace = "http://sphinx.dat.de/services/VehicleSelectionService", className = "de.dat.datecodeselection.services.vehicleselectionservice.GetHgvPlatformBaseModelsResponse")
    @Action(input = "getHgvPlatformBaseModels", output = "http://sphinx.dat.de/services/VehicleSelectionService/VehicleSelectionService/getHgvPlatformBaseModelsResponse")
    public List<IntegerStringPair> getHgvPlatformBaseModels(
        @WebParam(name = "request", targetNamespace = "")
        HgvPlatformBaseModelSelectionRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns java.util.List<de.dat.datecodeselection.services.vehicleselectionservice.IntegerStringPair>
     */
    @WebMethod(action = "getHgvPlatformSubModels")
    @WebResult(name = "hgvPlatformSubModel", targetNamespace = "")
    @RequestWrapper(localName = "getHgvPlatformSubModels", targetNamespace = "http://sphinx.dat.de/services/VehicleSelectionService", className = "de.dat.datecodeselection.services.vehicleselectionservice.GetHgvPlatformSubModels")
    @ResponseWrapper(localName = "getHgvPlatformSubModelsResponse", targetNamespace = "http://sphinx.dat.de/services/VehicleSelectionService", className = "de.dat.datecodeselection.services.vehicleselectionservice.GetHgvPlatformSubModelsResponse")
    @Action(input = "getHgvPlatformSubModels", output = "http://sphinx.dat.de/services/VehicleSelectionService/VehicleSelectionService/getHgvPlatformSubModelsResponse")
    public List<IntegerStringPair> getHgvPlatformSubModels(
        @WebParam(name = "request", targetNamespace = "")
        HgvPlatformSubModelSelectionRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns de.dat.datecodeselection.services.vehicleselectionservice.GetHgvPlatformSubModelDataResponse.VXS
     */
    @WebMethod(action = "getHgvPlatformSubModelData")
    @WebResult(name = "VXS", targetNamespace = "")
    @RequestWrapper(localName = "getHgvPlatformSubModelData", targetNamespace = "http://sphinx.dat.de/services/VehicleSelectionService", className = "de.dat.datecodeselection.services.vehicleselectionservice.GetHgvPlatformSubModelData")
    @ResponseWrapper(localName = "getHgvPlatformSubModelDataResponse", targetNamespace = "http://sphinx.dat.de/services/VehicleSelectionService", className = "de.dat.datecodeselection.services.vehicleselectionservice.GetHgvPlatformSubModelDataResponse")
    @Action(input = "getHgvPlatformSubModelData", output = "http://sphinx.dat.de/services/VehicleSelectionService/VehicleSelectionService/getHgvPlatformSubModelDataResponse")
    public de.dat.datecodeselection.services.vehicleselectionservice.GetHgvPlatformSubModelDataResponse.VXS getHgvPlatformSubModelData(
        @WebParam(name = "request", targetNamespace = "")
        HgvPlatformSubModelDataRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns java.util.List<de.dat.datecodeselection.services.vehicleselectionservice.IntegerStringPair>
     */
    @WebMethod(action = "getHgvPlatformAggregateModels")
    @WebResult(name = "hgvPlatformAggregateModel", targetNamespace = "")
    @RequestWrapper(localName = "getHgvPlatformAggregateModels", targetNamespace = "http://sphinx.dat.de/services/VehicleSelectionService", className = "de.dat.datecodeselection.services.vehicleselectionservice.GetHgvPlatformAggregateModels")
    @ResponseWrapper(localName = "getHgvPlatformAggregateModelsResponse", targetNamespace = "http://sphinx.dat.de/services/VehicleSelectionService", className = "de.dat.datecodeselection.services.vehicleselectionservice.GetHgvPlatformAggregateModelsResponse")
    @Action(input = "getHgvPlatformAggregateModels", output = "http://sphinx.dat.de/services/VehicleSelectionService/VehicleSelectionService/getHgvPlatformAggregateModelsResponse")
    public List<IntegerStringPair> getHgvPlatformAggregateModels(
        @WebParam(name = "request", targetNamespace = "")
        HgvPlatformAggregateModelSelectionRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns de.dat.datecodeselection.services.vehicleselectionservice.GetHgvPlatformAggregateModelDataResponse.VXS
     */
    @WebMethod(action = "getHgvPlatformAggregateModelData")
    @WebResult(name = "VXS", targetNamespace = "")
    @RequestWrapper(localName = "getHgvPlatformAggregateModelData", targetNamespace = "http://sphinx.dat.de/services/VehicleSelectionService", className = "de.dat.datecodeselection.services.vehicleselectionservice.GetHgvPlatformAggregateModelData")
    @ResponseWrapper(localName = "getHgvPlatformAggregateModelDataResponse", targetNamespace = "http://sphinx.dat.de/services/VehicleSelectionService", className = "de.dat.datecodeselection.services.vehicleselectionservice.GetHgvPlatformAggregateModelDataResponse")
    @Action(input = "getHgvPlatformAggregateModelData", output = "http://sphinx.dat.de/services/VehicleSelectionService/VehicleSelectionService/getHgvPlatformAggregateModelDataResponse")
    public de.dat.datecodeselection.services.vehicleselectionservice.GetHgvPlatformAggregateModelDataResponse.VXS getHgvPlatformAggregateModelData(
        @WebParam(name = "request", targetNamespace = "")
        HgvPlatformAggregateModelDataRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns java.util.List<java.lang.Integer>
     */
    @WebMethod(action = "getClassificationGroups")
    @WebResult(name = "classificationGroup", targetNamespace = "")
    @RequestWrapper(localName = "getClassificationGroups", targetNamespace = "http://sphinx.dat.de/services/VehicleSelectionService", className = "de.dat.datecodeselection.services.vehicleselectionservice.GetClassificationGroups")
    @ResponseWrapper(localName = "getClassificationGroupsResponse", targetNamespace = "http://sphinx.dat.de/services/VehicleSelectionService", className = "de.dat.datecodeselection.services.vehicleselectionservice.GetClassificationGroupsResponse")
    @Action(input = "getClassificationGroups", output = "http://sphinx.dat.de/services/VehicleSelectionService/VehicleSelectionService/getClassificationGroupsResponse")
    public List<Integer> getClassificationGroups(
        @WebParam(name = "request", targetNamespace = "")
        SubTypeVariantSelectionRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns java.util.List<de.dat.datecodeselection.services.vehicleselectionservice.IntegerStringPair>
     */
    @WebMethod(action = "getCarBodyOptions")
    @WebResult(name = "carBodyOption", targetNamespace = "")
    @RequestWrapper(localName = "getCarBodyOptions", targetNamespace = "http://sphinx.dat.de/services/VehicleSelectionService", className = "de.dat.datecodeselection.services.vehicleselectionservice.GetCarBodyOptions")
    @ResponseWrapper(localName = "getCarBodyOptionsResponse", targetNamespace = "http://sphinx.dat.de/services/VehicleSelectionService", className = "de.dat.datecodeselection.services.vehicleselectionservice.GetCarBodyOptionsResponse")
    @Action(input = "getCarBodyOptions", output = "http://sphinx.dat.de/services/VehicleSelectionService/VehicleSelectionService/getCarBodyOptionsResponse")
    public List<IntegerStringPair> getCarBodyOptions(
        @WebParam(name = "request", targetNamespace = "")
        SubTypeVariantEquipmentSelectionRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns java.util.List<de.dat.datecodeselection.services.vehicleselectionservice.IntegerStringPair>
     */
    @WebMethod(action = "getConstructionOptions")
    @WebResult(name = "constructionOption", targetNamespace = "")
    @RequestWrapper(localName = "getConstructionOptions", targetNamespace = "http://sphinx.dat.de/services/VehicleSelectionService", className = "de.dat.datecodeselection.services.vehicleselectionservice.GetConstructionOptions")
    @ResponseWrapper(localName = "getConstructionOptionsResponse", targetNamespace = "http://sphinx.dat.de/services/VehicleSelectionService", className = "de.dat.datecodeselection.services.vehicleselectionservice.GetConstructionOptionsResponse")
    @Action(input = "getConstructionOptions", output = "http://sphinx.dat.de/services/VehicleSelectionService/VehicleSelectionService/getConstructionOptionsResponse")
    public List<IntegerStringPair> getConstructionOptions(
        @WebParam(name = "request", targetNamespace = "")
        SubTypeVariantEquipmentSelectionRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns java.util.List<de.dat.datecodeselection.services.vehicleselectionservice.IntegerStringPair>
     */
    @WebMethod(action = "getDriversCabOptions")
    @WebResult(name = "driversCabOption", targetNamespace = "")
    @RequestWrapper(localName = "getDriversCabOptions", targetNamespace = "http://sphinx.dat.de/services/VehicleSelectionService", className = "de.dat.datecodeselection.services.vehicleselectionservice.GetDriversCabOptions")
    @ResponseWrapper(localName = "getDriversCabOptionsResponse", targetNamespace = "http://sphinx.dat.de/services/VehicleSelectionService", className = "de.dat.datecodeselection.services.vehicleselectionservice.GetDriversCabOptionsResponse")
    @Action(input = "getDriversCabOptions", output = "http://sphinx.dat.de/services/VehicleSelectionService/VehicleSelectionService/getDriversCabOptionsResponse")
    public List<IntegerStringPair> getDriversCabOptions(
        @WebParam(name = "request", targetNamespace = "")
        SubTypeVariantEquipmentSelectionRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns java.util.List<de.dat.datecodeselection.services.vehicleselectionservice.IntegerStringPair>
     */
    @WebMethod(action = "getEquipmentLineOptions")
    @WebResult(name = "equipmentLineOption", targetNamespace = "")
    @RequestWrapper(localName = "getEquipmentLineOptions", targetNamespace = "http://sphinx.dat.de/services/VehicleSelectionService", className = "de.dat.datecodeselection.services.vehicleselectionservice.GetEquipmentLineOptions")
    @ResponseWrapper(localName = "getEquipmentLineOptionsResponse", targetNamespace = "http://sphinx.dat.de/services/VehicleSelectionService", className = "de.dat.datecodeselection.services.vehicleselectionservice.GetEquipmentLineOptionsResponse")
    @Action(input = "getEquipmentLineOptions", output = "http://sphinx.dat.de/services/VehicleSelectionService/VehicleSelectionService/getEquipmentLineOptionsResponse")
    public List<IntegerStringPair> getEquipmentLineOptions(
        @WebParam(name = "request", targetNamespace = "")
        SubTypeVariantEquipmentSelectionRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns java.util.List<de.dat.datecodeselection.services.vehicleselectionservice.IntegerStringPair>
     */
    @WebMethod(action = "getGearingOptions")
    @WebResult(name = "gearingOption", targetNamespace = "")
    @RequestWrapper(localName = "getGearingOptions", targetNamespace = "http://sphinx.dat.de/services/VehicleSelectionService", className = "de.dat.datecodeselection.services.vehicleselectionservice.GetGearingOptions")
    @ResponseWrapper(localName = "getGearingOptionsResponse", targetNamespace = "http://sphinx.dat.de/services/VehicleSelectionService", className = "de.dat.datecodeselection.services.vehicleselectionservice.GetGearingOptionsResponse")
    @Action(input = "getGearingOptions", output = "http://sphinx.dat.de/services/VehicleSelectionService/VehicleSelectionService/getGearingOptionsResponse")
    public List<IntegerStringPair> getGearingOptions(
        @WebParam(name = "request", targetNamespace = "")
        SubTypeVariantEquipmentSelectionRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns java.util.List<de.dat.datecodeselection.services.vehicleselectionservice.IntegerStringPair>
     */
    @WebMethod(action = "getGrossVehicleWeightOptions")
    @WebResult(name = "grossVehicleWeightOption", targetNamespace = "")
    @RequestWrapper(localName = "getGrossVehicleWeightOptions", targetNamespace = "http://sphinx.dat.de/services/VehicleSelectionService", className = "de.dat.datecodeselection.services.vehicleselectionservice.GetGrossVehicleWeightOptions")
    @ResponseWrapper(localName = "getGrossVehicleWeightOptionsResponse", targetNamespace = "http://sphinx.dat.de/services/VehicleSelectionService", className = "de.dat.datecodeselection.services.vehicleselectionservice.GetGrossVehicleWeightOptionsResponse")
    @Action(input = "getGrossVehicleWeightOptions", output = "http://sphinx.dat.de/services/VehicleSelectionService/VehicleSelectionService/getGrossVehicleWeightOptionsResponse")
    public List<IntegerStringPair> getGrossVehicleWeightOptions(
        @WebParam(name = "request", targetNamespace = "")
        SubTypeVariantEquipmentSelectionRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns java.util.List<de.dat.datecodeselection.services.vehicleselectionservice.IntegerStringPair>
     */
    @WebMethod(action = "getNumberOfAxleOptions")
    @WebResult(name = "numberOfAxleOption", targetNamespace = "")
    @RequestWrapper(localName = "getNumberOfAxleOptions", targetNamespace = "http://sphinx.dat.de/services/VehicleSelectionService", className = "de.dat.datecodeselection.services.vehicleselectionservice.GetNumberOfAxleOptions")
    @ResponseWrapper(localName = "getNumberOfAxleOptionsResponse", targetNamespace = "http://sphinx.dat.de/services/VehicleSelectionService", className = "de.dat.datecodeselection.services.vehicleselectionservice.GetNumberOfAxleOptionsResponse")
    @Action(input = "getNumberOfAxleOptions", output = "http://sphinx.dat.de/services/VehicleSelectionService/VehicleSelectionService/getNumberOfAxleOptionsResponse")
    public List<IntegerStringPair> getNumberOfAxleOptions(
        @WebParam(name = "request", targetNamespace = "")
        SubTypeVariantEquipmentSelectionRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns java.util.List<de.dat.datecodeselection.services.vehicleselectionservice.IntegerStringPair>
     */
    @WebMethod(action = "getSuspensionOptions")
    @WebResult(name = "suspensionOption", targetNamespace = "")
    @RequestWrapper(localName = "getSuspensionOptions", targetNamespace = "http://sphinx.dat.de/services/VehicleSelectionService", className = "de.dat.datecodeselection.services.vehicleselectionservice.GetSuspensionOptions")
    @ResponseWrapper(localName = "getSuspensionOptionsResponse", targetNamespace = "http://sphinx.dat.de/services/VehicleSelectionService", className = "de.dat.datecodeselection.services.vehicleselectionservice.GetSuspensionOptionsResponse")
    @Action(input = "getSuspensionOptions", output = "http://sphinx.dat.de/services/VehicleSelectionService/VehicleSelectionService/getSuspensionOptionsResponse")
    public List<IntegerStringPair> getSuspensionOptions(
        @WebParam(name = "request", targetNamespace = "")
        SubTypeVariantEquipmentSelectionRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns java.util.List<de.dat.datecodeselection.services.vehicleselectionservice.IntegerStringPair>
     */
    @WebMethod(action = "getTypeOfDriveOptions")
    @WebResult(name = "typeOfDriveOption", targetNamespace = "")
    @RequestWrapper(localName = "getTypeOfDriveOptions", targetNamespace = "http://sphinx.dat.de/services/VehicleSelectionService", className = "de.dat.datecodeselection.services.vehicleselectionservice.GetTypeOfDriveOptions")
    @ResponseWrapper(localName = "getTypeOfDriveOptionsResponse", targetNamespace = "http://sphinx.dat.de/services/VehicleSelectionService", className = "de.dat.datecodeselection.services.vehicleselectionservice.GetTypeOfDriveOptionsResponse")
    @Action(input = "getTypeOfDriveOptions", output = "http://sphinx.dat.de/services/VehicleSelectionService/VehicleSelectionService/getTypeOfDriveOptionsResponse")
    public List<IntegerStringPair> getTypeOfDriveOptions(
        @WebParam(name = "request", targetNamespace = "")
        SubTypeVariantEquipmentSelectionRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns java.util.List<de.dat.datecodeselection.services.vehicleselectionservice.IntegerStringPair>
     */
    @WebMethod(action = "getWheelBaseOptions")
    @WebResult(name = "wheelBaseOption", targetNamespace = "")
    @RequestWrapper(localName = "getWheelBaseOptions", targetNamespace = "http://sphinx.dat.de/services/VehicleSelectionService", className = "de.dat.datecodeselection.services.vehicleselectionservice.GetWheelBaseOptions")
    @ResponseWrapper(localName = "getWheelBaseOptionsResponse", targetNamespace = "http://sphinx.dat.de/services/VehicleSelectionService", className = "de.dat.datecodeselection.services.vehicleselectionservice.GetWheelBaseOptionsResponse")
    @Action(input = "getWheelBaseOptions", output = "http://sphinx.dat.de/services/VehicleSelectionService/VehicleSelectionService/getWheelBaseOptionsResponse")
    public List<IntegerStringPair> getWheelBaseOptions(
        @WebParam(name = "request", targetNamespace = "")
        SubTypeVariantEquipmentSelectionRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns java.util.List<de.dat.datecodeselection.services.vehicleselectionservice.IntegerStringPair>
     */
    @WebMethod(action = "getOptionsbyClassification")
    @WebResult(name = "options", targetNamespace = "")
    @RequestWrapper(localName = "getOptionsbyClassification", targetNamespace = "http://sphinx.dat.de/services/VehicleSelectionService", className = "de.dat.datecodeselection.services.vehicleselectionservice.GetOptionsbyClassification")
    @ResponseWrapper(localName = "getOptionsbyClassificationResponse", targetNamespace = "http://sphinx.dat.de/services/VehicleSelectionService", className = "de.dat.datecodeselection.services.vehicleselectionservice.GetOptionsbyClassificationResponse")
    @Action(input = "getOptionsbyClassification", output = "http://sphinx.dat.de/services/VehicleSelectionService/VehicleSelectionService/getOptionsbyClassificationResponse")
    public List<IntegerStringPair> getOptionsbyClassification(
        @WebParam(name = "request", targetNamespace = "")
        SubTypeVariantClassifiedEquipmentSelectionRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns java.util.List<de.dat.datecodeselection.services.vehicleselectionservice.StringStringPair>
     */
    @WebMethod(action = "getPriceFocusCases")
    @WebResult(name = "priceFocusCase", targetNamespace = "")
    @RequestWrapper(localName = "getPriceFocusCases", targetNamespace = "http://sphinx.dat.de/services/VehicleSelectionService", className = "de.dat.datecodeselection.services.vehicleselectionservice.GetPriceFocusCases")
    @ResponseWrapper(localName = "getPriceFocusCasesResponse", targetNamespace = "http://sphinx.dat.de/services/VehicleSelectionService", className = "de.dat.datecodeselection.services.vehicleselectionservice.GetPriceFocusCasesResponse")
    @Action(input = "getPriceFocusCases", output = "http://sphinx.dat.de/services/VehicleSelectionService/VehicleSelectionService/getPriceFocusCasesResponse")
    public List<StringStringPair> getPriceFocusCases(
        @WebParam(name = "request", targetNamespace = "")
        PriceFocusSelectionRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns de.dat.datecodeselection.services.vehicleselectionservice.ConstructionTimePeriod
     */
    @WebMethod(action = "getConstructionPeriodsN")
    @WebResult(name = "constructionPeriodN", targetNamespace = "")
    @RequestWrapper(localName = "getConstructionPeriodsN", targetNamespace = "http://sphinx.dat.de/services/VehicleSelectionService", className = "de.dat.datecodeselection.services.vehicleselectionservice.GetConstructionPeriodsN")
    @ResponseWrapper(localName = "getConstructionPeriodsNResponse", targetNamespace = "http://sphinx.dat.de/services/VehicleSelectionService", className = "de.dat.datecodeselection.services.vehicleselectionservice.GetConstructionPeriodsNResponse")
    @Action(input = "getConstructionPeriodsN", output = "http://sphinx.dat.de/services/VehicleSelectionService/VehicleSelectionService/getConstructionPeriodsNResponse")
    public ConstructionTimePeriod getConstructionPeriodsN(
        @WebParam(name = "request", targetNamespace = "")
        ConstructionPeriodSelectionRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns de.dat.datecodeselection.services.vehicleselectionservice.GetVehicleDataResponse.VXS
     */
    @WebMethod(action = "getVehicleData")
    @WebResult(name = "VXS", targetNamespace = "")
    @RequestWrapper(localName = "getVehicleData", targetNamespace = "http://sphinx.dat.de/services/VehicleSelectionService", className = "de.dat.datecodeselection.services.vehicleselectionservice.GetVehicleData")
    @ResponseWrapper(localName = "getVehicleDataResponse", targetNamespace = "http://sphinx.dat.de/services/VehicleSelectionService", className = "de.dat.datecodeselection.services.vehicleselectionservice.GetVehicleDataResponse")
    @Action(input = "getVehicleData", output = "http://sphinx.dat.de/services/VehicleSelectionService/VehicleSelectionService/getVehicleDataResponse")
    public de.dat.datecodeselection.services.vehicleselectionservice.GetVehicleDataResponse.VXS getVehicleData(
        @WebParam(name = "request", targetNamespace = "")
        VehicleDataSelectionRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns java.util.List<de.dat.datecodeselection.services.vehicleselectionservice.IntegerStringPair>
     */
    @WebMethod(action = "getHgvPlatformAggregateManufacturers")
    @WebResult(name = "hgvPlatformAggregateManufacturer", targetNamespace = "")
    @RequestWrapper(localName = "getHgvPlatformAggregateManufacturers", targetNamespace = "http://sphinx.dat.de/services/VehicleSelectionService", className = "de.dat.datecodeselection.services.vehicleselectionservice.GetHgvPlatformAggregateManufacturers")
    @ResponseWrapper(localName = "getHgvPlatformAggregateManufacturersResponse", targetNamespace = "http://sphinx.dat.de/services/VehicleSelectionService", className = "de.dat.datecodeselection.services.vehicleselectionservice.GetHgvPlatformAggregateManufacturersResponse")
    @Action(input = "getHgvPlatformAggregateManufacturers", output = "http://sphinx.dat.de/services/VehicleSelectionService/VehicleSelectionService/getHgvPlatformAggregateManufacturersResponse")
    public List<IntegerStringPair> getHgvPlatformAggregateManufacturers(
        @WebParam(name = "request", targetNamespace = "")
        AbstractSelectionRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns java.util.List<de.dat.datecodeselection.services.vehicleselectionservice.IntegerStringPair>
     */
    @WebMethod(action = "getSubModels")
    @WebResult(name = "subModel", targetNamespace = "")
    @RequestWrapper(localName = "getSubModels", targetNamespace = "http://sphinx.dat.de/services/VehicleSelectionService", className = "de.dat.datecodeselection.services.vehicleselectionservice.GetSubModels")
    @ResponseWrapper(localName = "getSubModelsResponse", targetNamespace = "http://sphinx.dat.de/services/VehicleSelectionService", className = "de.dat.datecodeselection.services.vehicleselectionservice.GetSubModelsResponse")
    @Action(input = "getSubModels", output = "http://sphinx.dat.de/services/VehicleSelectionService/VehicleSelectionService/getSubModelsResponse")
    public List<IntegerStringPair> getSubModels(
        @WebParam(name = "request", targetNamespace = "")
        SubModelSelectionRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns java.util.List<de.dat.datecodeselection.services.vehicleselectionservice.IntegerStringPair>
     */
    @WebMethod(action = "getEngineOptions")
    @WebResult(name = "engineOption", targetNamespace = "")
    @RequestWrapper(localName = "getEngineOptions", targetNamespace = "http://sphinx.dat.de/services/VehicleSelectionService", className = "de.dat.datecodeselection.services.vehicleselectionservice.GetEngineOptions")
    @ResponseWrapper(localName = "getEngineOptionsResponse", targetNamespace = "http://sphinx.dat.de/services/VehicleSelectionService", className = "de.dat.datecodeselection.services.vehicleselectionservice.GetEngineOptionsResponse")
    @Action(input = "getEngineOptions", output = "http://sphinx.dat.de/services/VehicleSelectionService/VehicleSelectionService/getEngineOptionsResponse")
    public List<IntegerStringPair> getEngineOptions(
        @WebParam(name = "request", targetNamespace = "")
        SubTypeVariantEquipmentSelectionRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "compileDatECode")
    @WebResult(name = "datECode", targetNamespace = "")
    @RequestWrapper(localName = "compileDatECode", targetNamespace = "http://sphinx.dat.de/services/VehicleSelectionService", className = "de.dat.datecodeselection.services.vehicleselectionservice.CompileDatECode")
    @ResponseWrapper(localName = "compileDatECodeResponse", targetNamespace = "http://sphinx.dat.de/services/VehicleSelectionService", className = "de.dat.datecodeselection.services.vehicleselectionservice.CompileDatECodeResponse")
    @Action(input = "compileDatECode", output = "http://sphinx.dat.de/services/VehicleSelectionService/VehicleSelectionService/compileDatECodeResponse")
    public String compileDatECode(
        @WebParam(name = "request", targetNamespace = "")
        SubTypeVariantNumberSelectionRequest request);

}
