
package de.dat.myclaim.soap.valuationservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ValidationException", targetNamespace = "http://www.dat.eu/myClaim/soap/v2/ValuationService")
public class ValidationException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ValidationException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ValidationException_Exception(String message, ValidationException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public ValidationException_Exception(String message, ValidationException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: de.dat.myclaim.soap.valuationservice.ValidationException
     */
    public ValidationException getFaultInfo() {
        return faultInfo;
    }

}
