
package de.dat.myclaim.soap.valuationservice;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ValuationService", targetNamespace = "http://www.dat.eu/myClaim/soap/v2/ValuationService")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ValuationService {


    /**
     * 
     * @param coverage
     * @param contractID
     * @return
     *     returns de.dat.myclaim.soap.valuationservice.ResetValuation2DefaultResponse.VXS
     */
    @WebMethod(operationName = "resetValuation2default", action = "resetValuation2default")
    @WebResult(name = "VXS", targetNamespace = "")
    @RequestWrapper(localName = "resetValuation2default", targetNamespace = "http://www.dat.eu/myClaim/soap/v2/ValuationService", className = "de.dat.myclaim.soap.valuationservice.ResetValuation2Default")
    @ResponseWrapper(localName = "resetValuation2defaultResponse", targetNamespace = "http://www.dat.eu/myClaim/soap/v2/ValuationService", className = "de.dat.myclaim.soap.valuationservice.ResetValuation2DefaultResponse")
    @Action(input = "resetValuation2default", output = "http://www.dat.eu/myClaim/soap/v2/ValuationService/ValuationService/resetValuation2defaultResponse")
    public de.dat.myclaim.soap.valuationservice.ResetValuation2DefaultResponse.VXS resetValuation2Default(
        @WebParam(name = "contractID", targetNamespace = "")
        long contractID,
        @WebParam(name = "Coverage", targetNamespace = "")
        String coverage);

    /**
     * 
     * @param coverage
     * @param contractID
     * @param dossier
     * @return
     *     returns de.dat.myclaim.soap.valuationservice.ChangeValuationResponse.VXS
     */
    @WebMethod(action = "changeValuation")
    @WebResult(name = "VXS", targetNamespace = "")
    @RequestWrapper(localName = "changeValuation", targetNamespace = "http://www.dat.eu/myClaim/soap/v2/ValuationService", className = "de.dat.myclaim.soap.valuationservice.ChangeValuation")
    @ResponseWrapper(localName = "changeValuationResponse", targetNamespace = "http://www.dat.eu/myClaim/soap/v2/ValuationService", className = "de.dat.myclaim.soap.valuationservice.ChangeValuationResponse")
    @Action(input = "changeValuation", output = "http://www.dat.eu/myClaim/soap/v2/ValuationService/ValuationService/changeValuationResponse")
    public de.dat.myclaim.soap.valuationservice.ChangeValuationResponse.VXS changeValuation(
        @WebParam(name = "contractID", targetNamespace = "")
        long contractID,
        @WebParam(name = "Dossier", targetNamespace = "http://www.dat.de/vxs")
        Dossier dossier,
        @WebParam(name = "Coverage", targetNamespace = "")
        String coverage);

    /**
     * 
     * @param coverage
     * @param dossier
     * @return
     *     returns de.dat.myclaim.soap.valuationservice.DoValuationInMemoryResponse.VXS
     */
    @WebMethod(action = "doValuationInMemory")
    @WebResult(name = "VXS", targetNamespace = "")
    @RequestWrapper(localName = "doValuationInMemory", targetNamespace = "http://www.dat.eu/myClaim/soap/v2/ValuationService", className = "de.dat.myclaim.soap.valuationservice.DoValuationInMemory")
    @ResponseWrapper(localName = "doValuationInMemoryResponse", targetNamespace = "http://www.dat.eu/myClaim/soap/v2/ValuationService", className = "de.dat.myclaim.soap.valuationservice.DoValuationInMemoryResponse")
    @Action(input = "doValuationInMemory", output = "http://www.dat.eu/myClaim/soap/v2/ValuationService/ValuationService/doValuationInMemoryResponse")
    public de.dat.myclaim.soap.valuationservice.DoValuationInMemoryResponse.VXS doValuationInMemory(
        @WebParam(name = "Dossier", targetNamespace = "http://www.dat.de/vxs")
        Dossier dossier,
        @WebParam(name = "Coverage", targetNamespace = "")
        String coverage);

    /**
     * 
     * @param request
     * @return
     *     returns java.util.List<de.dat.myclaim.soap.valuationservice.Region>
     */
    @WebMethod(action = "getRegionsOfCountry")
    @WebResult(name = "region", targetNamespace = "")
    @RequestWrapper(localName = "getRegionsOfCountry", targetNamespace = "http://www.dat.eu/myClaim/soap/v2/ValuationService", className = "de.dat.myclaim.soap.valuationservice.GetRegionsOfCountry")
    @ResponseWrapper(localName = "getRegionsOfCountryResponse", targetNamespace = "http://www.dat.eu/myClaim/soap/v2/ValuationService", className = "de.dat.myclaim.soap.valuationservice.GetRegionsOfCountryResponse")
    @Action(input = "getRegionsOfCountry", output = "http://www.dat.eu/myClaim/soap/v2/ValuationService/ValuationService/getRegionsOfCountryResponse")
    public List<Region> getRegionsOfCountry(
        @WebParam(name = "request", targetNamespace = "")
        YearMonthsForCountryRequest request);

    /**
     * 
     * @param dossierId
     * @param networkType
     */
    @WebMethod(action = "internalServiceDataExchange")
    @RequestWrapper(localName = "internalServiceDataExchange", targetNamespace = "http://www.dat.eu/myClaim/soap/v2/ValuationService", className = "de.dat.myclaim.soap.valuationservice.InternalServiceDataExchange")
    @ResponseWrapper(localName = "internalServiceDataExchangeResponse", targetNamespace = "http://www.dat.eu/myClaim/soap/v2/ValuationService", className = "de.dat.myclaim.soap.valuationservice.InternalServiceDataExchangeResponse")
    @Action(input = "internalServiceDataExchange", output = "http://www.dat.eu/myClaim/soap/v2/ValuationService/ValuationService/internalServiceDataExchangeResponse")
    public void internalServiceDataExchange(
        @WebParam(name = "DossierId", targetNamespace = "")
        long dossierId,
        @WebParam(name = "networkType", targetNamespace = "")
        String networkType);

    /**
     * 
     * @param coverage
     * @param contractType
     * @param dossier
     * @param contractId
     * @param templateData
     * @param networkType
     * @param templateId
     * @return
     *     returns de.dat.myclaim.soap.valuationservice.CreateValuationResponse.VXS
     * @throws ValidationException_Exception
     */
    @WebMethod(action = "createValuation")
    @WebResult(name = "VXS", targetNamespace = "")
    @RequestWrapper(localName = "createValuation", targetNamespace = "http://www.dat.eu/myClaim/soap/v2/ValuationService", className = "de.dat.myclaim.soap.valuationservice.CreateValuation")
    @ResponseWrapper(localName = "createValuationResponse", targetNamespace = "http://www.dat.eu/myClaim/soap/v2/ValuationService", className = "de.dat.myclaim.soap.valuationservice.CreateValuationResponse")
    @Action(input = "createValuation", output = "http://www.dat.eu/myClaim/soap/v2/ValuationService/ValuationService/createValuationResponse", fault = {
        @FaultAction(className = ValidationException_Exception.class, value = "http://www.dat.eu/myClaim/soap/v2/ValuationService/ValuationService/createValuation/Fault/ValidationException")
    })
    public de.dat.myclaim.soap.valuationservice.CreateValuationResponse.VXS createValuation(
        @WebParam(name = "Dossier", targetNamespace = "http://www.dat.de/vxs")
        Dossier dossier,
        @WebParam(name = "contractId", targetNamespace = "")
        Long contractId,
        @WebParam(name = "contractType", targetNamespace = "")
        String contractType,
        @WebParam(name = "networkType", targetNamespace = "")
        String networkType,
        @WebParam(name = "Coverage", targetNamespace = "")
        String coverage,
        @WebParam(name = "templateId", targetNamespace = "")
        Long templateId,
        @WebParam(name = "templateData", targetNamespace = "")
        de.dat.myclaim.soap.valuationservice.CreateValuation.TemplateData templateData)
        throws ValidationException_Exception
    ;

    /**
     * 
     * @param coverage
     * @param contractID
     * @return
     *     returns de.dat.myclaim.soap.valuationservice.GetValuationResponse.VXS
     */
    @WebMethod(action = "getValuation")
    @WebResult(name = "VXS", targetNamespace = "")
    @RequestWrapper(localName = "getValuation", targetNamespace = "http://www.dat.eu/myClaim/soap/v2/ValuationService", className = "de.dat.myclaim.soap.valuationservice.GetValuation")
    @ResponseWrapper(localName = "getValuationResponse", targetNamespace = "http://www.dat.eu/myClaim/soap/v2/ValuationService", className = "de.dat.myclaim.soap.valuationservice.GetValuationResponse")
    @Action(input = "getValuation", output = "http://www.dat.eu/myClaim/soap/v2/ValuationService/ValuationService/getValuationResponse")
    public de.dat.myclaim.soap.valuationservice.GetValuationResponse.VXS getValuation(
        @WebParam(name = "contractID", targetNamespace = "")
        long contractID,
        @WebParam(name = "Coverage", targetNamespace = "")
        String coverage);

}
