
package de.dat.myclaim.soap.valuationservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ValuationService", targetNamespace = "http://www.dat.eu/myClaim/soap/v2/ValuationService", wsdlLocation = "http://www.dat.de/myClaim/soap/ValuationService?wsdl")
public class ValuationService_Service
    extends Service
{

    private final static URL VALUATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException VALUATIONSERVICE_EXCEPTION;
    private final static QName VALUATIONSERVICE_QNAME = new QName("http://www.dat.eu/myClaim/soap/v2/ValuationService", "ValuationService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://www.dat.de/myClaim/soap/ValuationService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VALUATIONSERVICE_WSDL_LOCATION = url;
        VALUATIONSERVICE_EXCEPTION = e;
    }

    public ValuationService_Service() {
        super(__getWsdlLocation(), VALUATIONSERVICE_QNAME);
    }

    public ValuationService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), VALUATIONSERVICE_QNAME, features);
    }

    public ValuationService_Service(URL wsdlLocation) {
        super(wsdlLocation, VALUATIONSERVICE_QNAME);
    }

    public ValuationService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VALUATIONSERVICE_QNAME, features);
    }

    public ValuationService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ValuationService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ValuationService
     */
    @WebEndpoint(name = "ValuationServicePort")
    public ValuationService getValuationServicePort() {
        return super.getPort(new QName("http://www.dat.eu/myClaim/soap/v2/ValuationService", "ValuationServicePort"), ValuationService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ValuationService
     */
    @WebEndpoint(name = "ValuationServicePort")
    public ValuationService getValuationServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.dat.eu/myClaim/soap/v2/ValuationService", "ValuationServicePort"), ValuationService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VALUATIONSERVICE_EXCEPTION!= null) {
            throw VALUATIONSERVICE_EXCEPTION;
        }
        return VALUATIONSERVICE_WSDL_LOCATION;
    }

}
