
package de.dat.vehiclerepaironline.services.vehiclerepairservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "VehicleRepairService", targetNamespace = "http://sphinx.dat.de/services/VehicleRepairService", wsdlLocation = "http://www.dat.de/VehicleRepairOnline/services/VehicleRepairService?wsdl")
public class VehicleRepairService_Service
    extends Service
{

    private final static URL VEHICLEREPAIRSERVICE_WSDL_LOCATION;
    private final static WebServiceException VEHICLEREPAIRSERVICE_EXCEPTION;
    private final static QName VEHICLEREPAIRSERVICE_QNAME = new QName("http://sphinx.dat.de/services/VehicleRepairService", "VehicleRepairService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://www.dat.de/VehicleRepairOnline/services/VehicleRepairService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VEHICLEREPAIRSERVICE_WSDL_LOCATION = url;
        VEHICLEREPAIRSERVICE_EXCEPTION = e;
    }

    public VehicleRepairService_Service() {
        super(__getWsdlLocation(), VEHICLEREPAIRSERVICE_QNAME);
    }

    public VehicleRepairService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), VEHICLEREPAIRSERVICE_QNAME, features);
    }

    public VehicleRepairService_Service(URL wsdlLocation) {
        super(wsdlLocation, VEHICLEREPAIRSERVICE_QNAME);
    }

    public VehicleRepairService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VEHICLEREPAIRSERVICE_QNAME, features);
    }

    public VehicleRepairService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VehicleRepairService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns VehicleRepairService
     */
    @WebEndpoint(name = "VehicleRepairServicePort")
    public VehicleRepairService getVehicleRepairServicePort() {
        return super.getPort(new QName("http://sphinx.dat.de/services/VehicleRepairService", "VehicleRepairServicePort"), VehicleRepairService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VehicleRepairService
     */
    @WebEndpoint(name = "VehicleRepairServicePort")
    public VehicleRepairService getVehicleRepairServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://sphinx.dat.de/services/VehicleRepairService", "VehicleRepairServicePort"), VehicleRepairService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VEHICLEREPAIRSERVICE_EXCEPTION!= null) {
            throw VEHICLEREPAIRSERVICE_EXCEPTION;
        }
        return VEHICLEREPAIRSERVICE_WSDL_LOCATION;
    }

}
