
package de.dat.myclaim.soap.myclaimexternalservice;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MyClaimExternalService", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MyClaimExternalService {


    /**
     * 
     * @param recipients
     * @param claimId
     * @param message
     * @return
     *     returns boolean
     */
    @WebMethod(action = "addMessage")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addMessage", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.AddMessage")
    @ResponseWrapper(localName = "addMessageResponse", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.AddMessageResponse")
    @Action(input = "addMessage", output = "http://www.dat.eu/myClaim/soap/MyClaimExternalService/MyClaimExternalService/addMessageResponse")
    public boolean addMessage(
        @WebParam(name = "claimId", targetNamespace = "")
        long claimId,
        @WebParam(name = "recipients", targetNamespace = "")
        List<CustomerRole> recipients,
        @WebParam(name = "message", targetNamespace = "")
        String message);

    /**
     * 
     * @param contractId
     * @param isWithHistoricalCalculations
     * @return
     *     returns de.dat.myclaim.soap.myclaimexternalservice.ContractDetails
     */
    @WebMethod(action = "getContract")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getContract", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.GetContract")
    @ResponseWrapper(localName = "getContractResponse", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.GetContractResponse")
    @Action(input = "getContract", output = "http://www.dat.eu/myClaim/soap/MyClaimExternalService/MyClaimExternalService/getContractResponse")
    public ContractDetails getContract(
        @WebParam(name = "contractId", targetNamespace = "")
        long contractId,
        @WebParam(name = "isWithHistoricalCalculations", targetNamespace = "")
        boolean isWithHistoricalCalculations);

    /**
     * 
     * @param templateTypes
     * @return
     *     returns java.util.List<de.dat.myclaim.soap.myclaimexternalservice.TemplateOverview>
     */
    @WebMethod(action = "listTemplates")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listTemplates", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.ListTemplates")
    @ResponseWrapper(localName = "listTemplatesResponse", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.ListTemplatesResponse")
    @Action(input = "listTemplates", output = "http://www.dat.eu/myClaim/soap/MyClaimExternalService/MyClaimExternalService/listTemplatesResponse")
    public List<TemplateOverview> listTemplates(
        @WebParam(name = "templateTypes", targetNamespace = "")
        List<String> templateTypes);

    /**
     * 
     * @param contractType
     * @param contractId
     * @param dossier
     * @param templateData
     * @param complexTemplateData
     * @param networkType
     * @param templateId
     * @return
     *     returns long
     */
    @WebMethod(action = "createOrUpdateContract")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createOrUpdateContract", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.CreateOrUpdateContract")
    @ResponseWrapper(localName = "createOrUpdateContractResponse", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.CreateOrUpdateContractResponse")
    @Action(input = "createOrUpdateContract", output = "http://www.dat.eu/myClaim/soap/MyClaimExternalService/MyClaimExternalService/createOrUpdateContractResponse")
    public long createOrUpdateContract(
        @WebParam(name = "contractId", targetNamespace = "")
        Long contractId,
        @WebParam(name = "contractType", targetNamespace = "")
        String contractType,
        @WebParam(name = "networkType", targetNamespace = "")
        String networkType,
        @WebParam(name = "dossier", targetNamespace = "http://www.dat.de/vxs")
        de.dat.myclaim.soap.myclaimexternalservice.Dossier dossier,
        @WebParam(name = "templateId", targetNamespace = "")
        Long templateId,
        @WebParam(name = "templateData", targetNamespace = "")
        de.dat.myclaim.soap.myclaimexternalservice.CreateOrUpdateContract.TemplateData templateData,
        @WebParam(name = "complexTemplateData", targetNamespace = "")
        ComplexTemplateData complexTemplateData);

    /**
     * 
     * @param senderRoles
     * @param contractId
     * @param historyEvent
     * @param producedFrom
     * @return
     *     returns java.util.List<de.dat.myclaim.soap.myclaimexternalservice.NotificationEvent>
     */
    @WebMethod(action = "listContractHistory")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listContractHistory", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.ListContractHistory")
    @ResponseWrapper(localName = "listContractHistoryResponse", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.ListContractHistoryResponse")
    @Action(input = "listContractHistory", output = "http://www.dat.eu/myClaim/soap/MyClaimExternalService/MyClaimExternalService/listContractHistoryResponse")
    public List<NotificationEvent> listContractHistory(
        @WebParam(name = "contractId", targetNamespace = "")
        long contractId,
        @WebParam(name = "producedFrom", targetNamespace = "")
        XMLGregorianCalendar producedFrom,
        @WebParam(name = "historyEvent", targetNamespace = "")
        HistoryEvent historyEvent,
        @WebParam(name = "senderRoles", targetNamespace = "")
        List<CustomerRole> senderRoles);

    /**
     * 
     * @param referenceNumber
     * @param partnerIdentification
     * @return
     *     returns java.util.List<java.lang.Long>
     */
    @WebMethod(action = "findContract")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findContract", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.FindContract")
    @ResponseWrapper(localName = "findContractResponse", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.FindContractResponse")
    @Action(input = "findContract", output = "http://www.dat.eu/myClaim/soap/MyClaimExternalService/MyClaimExternalService/findContractResponse")
    public List<Long> findContract(
        @WebParam(name = "referenceNumber", targetNamespace = "")
        String referenceNumber,
        @WebParam(name = "partnerIdentification", targetNamespace = "")
        String partnerIdentification);

    /**
     * 
     * @param zip
     * @param city
     * @param streetNr
     * @param street
     * @param isoCountryCode
     * @return
     *     returns de.dat.myclaim.soap.myclaimexternalservice.Location
     */
    @WebMethod(action = "getGeoCoordinates")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getGeoCoordinates", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.GetGeoCoordinates")
    @ResponseWrapper(localName = "getGeoCoordinatesResponse", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.GetGeoCoordinatesResponse")
    @Action(input = "getGeoCoordinates", output = "http://www.dat.eu/myClaim/soap/MyClaimExternalService/MyClaimExternalService/getGeoCoordinatesResponse")
    public Location getGeoCoordinates(
        @WebParam(name = "streetNr", targetNamespace = "")
        String streetNr,
        @WebParam(name = "street", targetNamespace = "")
        String street,
        @WebParam(name = "zip", targetNamespace = "")
        String zip,
        @WebParam(name = "city", targetNamespace = "")
        String city,
        @WebParam(name = "isoCountryCode", targetNamespace = "")
        String isoCountryCode);

    /**
     * 
     * @param networkType
     * @param customerNumbers
     * @return
     *     returns java.util.List<de.dat.myclaim.soap.myclaimexternalservice.LabourRatesItem>
     */
    @WebMethod(action = "listCoopLabourRates")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listCoopLabourRates", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.ListCoopLabourRates")
    @ResponseWrapper(localName = "listCoopLabourRatesResponse", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.ListCoopLabourRatesResponse")
    @Action(input = "listCoopLabourRates", output = "http://www.dat.eu/myClaim/soap/MyClaimExternalService/MyClaimExternalService/listCoopLabourRatesResponse")
    public List<LabourRatesItem> listCoopLabourRates(
        @WebParam(name = "customerNumbers", targetNamespace = "")
        List<String> customerNumbers,
        @WebParam(name = "networkType", targetNamespace = "")
        String networkType);

    /**
     * 
     * @param note
     * @param comments
     * @param statusType
     * @param contractId
     * @param templateData
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "changeContractStatus")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "changeContractStatus", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.ChangeContractStatus")
    @ResponseWrapper(localName = "changeContractStatusResponse", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.ChangeContractStatusResponse")
    @Action(input = "changeContractStatus", output = "http://www.dat.eu/myClaim/soap/MyClaimExternalService/MyClaimExternalService/changeContractStatusResponse")
    public String changeContractStatus(
        @WebParam(name = "contractId", targetNamespace = "")
        long contractId,
        @WebParam(name = "statusType", targetNamespace = "")
        String statusType,
        @WebParam(name = "note", targetNamespace = "")
        String note,
        @WebParam(name = "comments", targetNamespace = "")
        List<Comment> comments,
        @WebParam(name = "templateData", targetNamespace = "")
        de.dat.myclaim.soap.myclaimexternalservice.ChangeContractStatus.TemplateData templateData);

    /**
     * 
     * @param statusType
     * @param contractId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "changeContractStatusCSP")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "changeContractStatusCSP", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.ChangeContractStatusCSP")
    @ResponseWrapper(localName = "changeContractStatusCSPResponse", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.ChangeContractStatusCSPResponse")
    @Action(input = "changeContractStatusCSP", output = "http://www.dat.eu/myClaim/soap/MyClaimExternalService/MyClaimExternalService/changeContractStatusCSPResponse")
    public String changeContractStatusCSP(
        @WebParam(name = "contractId", targetNamespace = "")
        long contractId,
        @WebParam(name = "statusType", targetNamespace = "")
        String statusType);

    /**
     * 
     * @param contractId
     * @return
     *     returns de.dat.myclaim.soap.myclaimexternalservice.ContractStatus
     */
    @WebMethod(action = "getContractStatus")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getContractStatus", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.GetContractStatus")
    @ResponseWrapper(localName = "getContractStatusResponse", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.GetContractStatusResponse")
    @Action(input = "getContractStatus", output = "http://www.dat.eu/myClaim/soap/MyClaimExternalService/MyClaimExternalService/getContractStatusResponse")
    public ContractStatus getContractStatus(
        @WebParam(name = "contractId", targetNamespace = "")
        long contractId);

    /**
     * 
     * @param contractType
     * @param contractId
     * @param dossier
     * @param externalId
     * @param networkType
     * @return
     *     returns long
     */
    @WebMethod(action = "createContractForExternalId")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createContractForExternalId", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.CreateContractForExternalId")
    @ResponseWrapper(localName = "createContractForExternalIdResponse", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.CreateContractForExternalIdResponse")
    @Action(input = "createContractForExternalId", output = "http://www.dat.eu/myClaim/soap/MyClaimExternalService/MyClaimExternalService/createContractForExternalIdResponse")
    public long createContractForExternalId(
        @WebParam(name = "contractId", targetNamespace = "")
        Long contractId,
        @WebParam(name = "dossier", targetNamespace = "")
        de.dat.myclaim.soap.myclaimexternalservice.CreateContractForExternalId.Dossier dossier,
        @WebParam(name = "contractType", targetNamespace = "")
        String contractType,
        @WebParam(name = "networkType", targetNamespace = "")
        String networkType,
        @WebParam(name = "externalId", targetNamespace = "")
        String externalId);

    /**
     * 
     * @param pageLimit
     * @param folder
     * @param networkTypes
     * @param openedSince
     * @param pageOffset
     * @param contractTypes
     * @param attributes
     * @param statusesId
     * @param changedSince
     * @param partnersToRetrieve
     * @return
     *     returns java.util.List<de.dat.myclaim.soap.myclaimexternalservice.ContractOverview>
     */
    @WebMethod(action = "listContracts")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listContracts", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.ListContracts")
    @ResponseWrapper(localName = "listContractsResponse", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.ListContractsResponse")
    @Action(input = "listContracts", output = "http://www.dat.eu/myClaim/soap/MyClaimExternalService/MyClaimExternalService/listContractsResponse")
    public List<ContractOverview> listContracts(
        @WebParam(name = "statusesId", targetNamespace = "")
        List<Long> statusesId,
        @WebParam(name = "contractTypes", targetNamespace = "")
        List<String> contractTypes,
        @WebParam(name = "networkTypes", targetNamespace = "")
        List<String> networkTypes,
        @WebParam(name = "partnersToRetrieve", targetNamespace = "")
        List<String> partnersToRetrieve,
        @WebParam(name = "openedSince", targetNamespace = "")
        XMLGregorianCalendar openedSince,
        @WebParam(name = "changedSince", targetNamespace = "")
        XMLGregorianCalendar changedSince,
        @WebParam(name = "folder", targetNamespace = "")
        Long folder,
        @WebParam(name = "pageLimit", targetNamespace = "")
        int pageLimit,
        @WebParam(name = "pageOffset", targetNamespace = "")
        int pageOffset,
        @WebParam(name = "attributes", targetNamespace = "")
        ClaimAttributes attributes);

    /**
     * 
     * @param attachmentItem
     * @param contractId
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "uploadAttachmentByIdentification", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.UploadAttachmentByIdentification")
    @ResponseWrapper(localName = "uploadAttachmentByIdentificationResponse", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.UploadAttachmentByIdentificationResponse")
    @Action(input = "http://www.dat.eu/myClaim/soap/MyClaimExternalService/MyClaimExternalService/uploadAttachmentByIdentificationRequest", output = "http://www.dat.eu/myClaim/soap/MyClaimExternalService/MyClaimExternalService/uploadAttachmentByIdentificationResponse")
    public boolean uploadAttachmentByIdentification(
        @WebParam(name = "contractId", targetNamespace = "")
        long contractId,
        @WebParam(name = "attachmentItem", targetNamespace = "")
        AttachmentItem attachmentItem);

    /**
     * 
     * @param referenceNumber
     * @param claimId
     * @param copySettings
     * @param templateId
     * @return
     *     returns java.lang.Long
     */
    @WebMethod(action = "copyClaim")
    @WebResult(name = "claimId", targetNamespace = "")
    @RequestWrapper(localName = "copyClaim", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.CopyClaim")
    @ResponseWrapper(localName = "copyClaimResponse", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.CopyClaimResponse")
    @Action(input = "copyClaim", output = "http://www.dat.eu/myClaim/soap/MyClaimExternalService/MyClaimExternalService/copyClaimResponse")
    public Long copyClaim(
        @WebParam(name = "claimId", targetNamespace = "")
        long claimId,
        @WebParam(name = "copySettings", targetNamespace = "")
        List<String> copySettings,
        @WebParam(name = "referenceNumber", targetNamespace = "")
        String referenceNumber,
        @WebParam(name = "templateId", targetNamespace = "")
        Long templateId);

    /**
     * 
     * @param attachmentItem
     * @param contractId
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "uploadAttachmentByFolderID", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.UploadAttachmentByFolderID")
    @ResponseWrapper(localName = "uploadAttachmentByFolderIDResponse", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.UploadAttachmentByFolderIDResponse")
    @Action(input = "http://www.dat.eu/myClaim/soap/MyClaimExternalService/MyClaimExternalService/uploadAttachmentByFolderIDRequest", output = "http://www.dat.eu/myClaim/soap/MyClaimExternalService/MyClaimExternalService/uploadAttachmentByFolderIDResponse")
    public boolean uploadAttachmentByFolderID(
        @WebParam(name = "contractId", targetNamespace = "")
        long contractId,
        @WebParam(name = "attachmentItem", targetNamespace = "")
        AttachmentItem attachmentItem);

    /**
     * 
     * @param contractId
     * @return
     *     returns de.dat.myclaim.soap.myclaimexternalservice.AttachmentFolders
     */
    @WebMethod(action = "listAttachmentFolders")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listAttachmentFolders", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.ListAttachmentFolders")
    @ResponseWrapper(localName = "listAttachmentFoldersResponse", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.ListAttachmentFoldersResponse")
    @Action(input = "listAttachmentFolders", output = "http://www.dat.eu/myClaim/soap/MyClaimExternalService/MyClaimExternalService/listAttachmentFoldersResponse")
    public AttachmentFolders listAttachmentFolders(
        @WebParam(name = "contractId", targetNamespace = "")
        long contractId);

    /**
     * 
     * @param contractId
     * @param userLogins
     * @return
     *     returns java.util.List<de.dat.myclaim.soap.myclaimexternalservice.UserListItem>
     */
    @WebMethod(action = "assignUsersToContract")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "assignUsersToContract", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.AssignUsersToContract")
    @ResponseWrapper(localName = "assignUsersToContractResponse", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.AssignUsersToContractResponse")
    @Action(input = "assignUsersToContract", output = "http://www.dat.eu/myClaim/soap/MyClaimExternalService/MyClaimExternalService/assignUsersToContractResponse")
    public List<UserListItem> assignUsersToContract(
        @WebParam(name = "contractId", targetNamespace = "")
        long contractId,
        @WebParam(name = "userLogins", targetNamespace = "")
        List<String> userLogins);

    /**
     * 
     * @param contractId
     * @param userLogins
     * @return
     *     returns java.util.List<de.dat.myclaim.soap.myclaimexternalservice.UserListItem>
     */
    @WebMethod(action = "unAssignUsersFromContract")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "unAssignUsersFromContract", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.UnAssignUsersFromContract")
    @ResponseWrapper(localName = "unAssignUsersFromContractResponse", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.UnAssignUsersFromContractResponse")
    @Action(input = "unAssignUsersFromContract", output = "http://www.dat.eu/myClaim/soap/MyClaimExternalService/MyClaimExternalService/unAssignUsersFromContractResponse")
    public List<UserListItem> unAssignUsersFromContract(
        @WebParam(name = "contractId", targetNamespace = "")
        long contractId,
        @WebParam(name = "userLogins", targetNamespace = "")
        List<String> userLogins);

    /**
     * 
     * @param postalCode
     * @param networkType
     * @param customerRole
     * @return
     *     returns java.util.List<de.dat.myclaim.soap.myclaimexternalservice.PartnerOverview>
     */
    @WebMethod(action = "listPartners")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listPartners", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.ListPartners")
    @ResponseWrapper(localName = "listPartnersResponse", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.ListPartnersResponse")
    @Action(input = "listPartners", output = "http://www.dat.eu/myClaim/soap/MyClaimExternalService/MyClaimExternalService/listPartnersResponse")
    public List<PartnerOverview> listPartners(
        @WebParam(name = "postalCode", targetNamespace = "")
        String postalCode,
        @WebParam(name = "customerRole", targetNamespace = "")
        String customerRole,
        @WebParam(name = "networkType", targetNamespace = "")
        String networkType);

    /**
     * 
     * @param templateTypes
     * @return
     *     returns java.util.List<de.dat.myclaim.soap.myclaimexternalservice.NetworkType>
     */
    @WebMethod(action = "(listAvailableNetworkTypes)")
    @WebResult(name = "networkType", targetNamespace = "")
    @RequestWrapper(localName = "listAvailableNetworkTypes", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.ListAvailableNetworkTypes")
    @ResponseWrapper(localName = "listAvailableNetworkTypesResponse", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.ListAvailableNetworkTypesResponse")
    @Action(input = "(listAvailableNetworkTypes)", output = "http://www.dat.eu/myClaim/soap/MyClaimExternalService/MyClaimExternalService/listAvailableNetworkTypesResponse")
    public List<NetworkType> listAvailableNetworkTypes(
        @WebParam(name = "templateTypes", targetNamespace = "")
        List<String> templateTypes);

    /**
     * 
     * @param contractId
     * @return
     *     returns java.util.List<de.dat.myclaim.soap.myclaimexternalservice.Address>
     */
    @WebMethod(action = "listCustomerAddresses")
    @WebResult(name = "customerAddresses", targetNamespace = "")
    @RequestWrapper(localName = "listCustomerAddresses", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.ListCustomerAddresses")
    @ResponseWrapper(localName = "listCustomerAddressesResponse", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.ListCustomerAddressesResponse")
    @Action(input = "listCustomerAddresses", output = "http://www.dat.eu/myClaim/soap/MyClaimExternalService/MyClaimExternalService/listCustomerAddressesResponse")
    public List<Address> listCustomerAddresses(
        @WebParam(name = "contractId", targetNamespace = "")
        Long contractId);

    /**
     * 
     * @param contractId
     * @param rolePartner
     * @return
     *     returns boolean
     */
    @WebMethod(action = "unAssignPartnerFromContract")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "unAssignPartnerFromContract", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.UnAssignPartnerFromContract")
    @ResponseWrapper(localName = "unAssignPartnerFromContractResponse", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.UnAssignPartnerFromContractResponse")
    @Action(input = "unAssignPartnerFromContract", output = "http://www.dat.eu/myClaim/soap/MyClaimExternalService/MyClaimExternalService/unAssignPartnerFromContractResponse")
    public boolean unAssignPartnerFromContract(
        @WebParam(name = "contractId", targetNamespace = "")
        long contractId,
        @WebParam(name = "rolePartner", targetNamespace = "")
        String rolePartner);

    /**
     * 
     * @param contractId
     * @param rolePartner
     * @param partnerId
     * @return
     *     returns boolean
     */
    @WebMethod(action = "assignPartnerToContract")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "assignPartnerToContract", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.AssignPartnerToContract")
    @ResponseWrapper(localName = "assignPartnerToContractResponse", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.AssignPartnerToContractResponse")
    @Action(input = "assignPartnerToContract", output = "http://www.dat.eu/myClaim/soap/MyClaimExternalService/MyClaimExternalService/assignPartnerToContractResponse")
    public boolean assignPartnerToContract(
        @WebParam(name = "contractId", targetNamespace = "")
        long contractId,
        @WebParam(name = "partnerId", targetNamespace = "")
        long partnerId,
        @WebParam(name = "rolePartner", targetNamespace = "")
        String rolePartner);

    /**
     * 
     * @param contractId
     * @param rolePartner
     * @param customerNumber
     * @return
     *     returns boolean
     */
    @WebMethod(action = "assignPartnerByCustomerNumber")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "assignPartnerByCustomerNumber", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.AssignPartnerByCustomerNumber")
    @ResponseWrapper(localName = "assignPartnerByCustomerNumberResponse", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.AssignPartnerByCustomerNumberResponse")
    @Action(input = "assignPartnerByCustomerNumber", output = "http://www.dat.eu/myClaim/soap/MyClaimExternalService/MyClaimExternalService/assignPartnerByCustomerNumberResponse")
    public boolean assignPartnerByCustomerNumber(
        @WebParam(name = "contractId", targetNamespace = "")
        long contractId,
        @WebParam(name = "customerNumber", targetNamespace = "")
        String customerNumber,
        @WebParam(name = "rolePartner", targetNamespace = "")
        String rolePartner);

    /**
     * 
     * @param internalIdentification
     * @param contractId
     * @param rolePartner
     * @return
     *     returns boolean
     */
    @WebMethod(action = "assignPartnerByInternalIdentification")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "assignPartnerByInternalIdentification", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.AssignPartnerByInternalIdentification")
    @ResponseWrapper(localName = "assignPartnerByInternalIdentificationResponse", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.AssignPartnerByInternalIdentificationResponse")
    @Action(input = "assignPartnerByInternalIdentification", output = "http://www.dat.eu/myClaim/soap/MyClaimExternalService/MyClaimExternalService/assignPartnerByInternalIdentificationResponse")
    public boolean assignPartnerByInternalIdentification(
        @WebParam(name = "contractId", targetNamespace = "")
        long contractId,
        @WebParam(name = "internalIdentification", targetNamespace = "")
        String internalIdentification,
        @WebParam(name = "rolePartner", targetNamespace = "")
        String rolePartner);

    /**
     * 
     * @param newerThan
     * @param documentTypes
     * @param contractId
     * @param attachmentTypes
     * @return
     *     returns java.util.List<de.dat.myclaim.soap.myclaimexternalservice.AttachmentItem>
     */
    @WebMethod(action = "listAttachmentsOfContract")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listAttachmentsOfContract", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.ListAttachmentsOfContract")
    @ResponseWrapper(localName = "listAttachmentsOfContractResponse", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.ListAttachmentsOfContractResponse")
    @Action(input = "listAttachmentsOfContract", output = "http://www.dat.eu/myClaim/soap/MyClaimExternalService/MyClaimExternalService/listAttachmentsOfContractResponse")
    public List<AttachmentItem> listAttachmentsOfContract(
        @WebParam(name = "contractId", targetNamespace = "")
        long contractId,
        @WebParam(name = "attachmentTypes", targetNamespace = "")
        List<String> attachmentTypes,
        @WebParam(name = "documentTypes", targetNamespace = "")
        List<String> documentTypes,
        @WebParam(name = "newerThan", targetNamespace = "")
        XMLGregorianCalendar newerThan);

    /**
     * 
     * @param contractId
     * @param rolePartner
     * @param settlementIdentification
     * @return
     *     returns boolean
     */
    @WebMethod(action = "assignSettlementToContract")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "assignSettlementToContract", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.AssignSettlementToContract")
    @ResponseWrapper(localName = "assignSettlementToContractResponse", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.AssignSettlementToContractResponse")
    @Action(input = "assignSettlementToContract", output = "http://www.dat.eu/myClaim/soap/MyClaimExternalService/MyClaimExternalService/assignSettlementToContractResponse")
    public boolean assignSettlementToContract(
        @WebParam(name = "contractId", targetNamespace = "")
        long contractId,
        @WebParam(name = "rolePartner", targetNamespace = "")
        String rolePartner,
        @WebParam(name = "settlementIdentification", targetNamespace = "")
        String settlementIdentification);

    /**
     * 
     * @param textSearchCriteria
     * @param distanceCalculationMode
     * @param rolePartner
     * @param location
     * @param network
     * @param brandsSearchCriteria
     * @return
     *     returns java.util.List<de.dat.myclaim.soap.myclaimexternalservice.PartnerList>
     */
    @WebMethod(action = "searchForPartners")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchForPartners", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.SearchForPartners")
    @ResponseWrapper(localName = "searchForPartnersResponse", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.SearchForPartnersResponse")
    @Action(input = "searchForPartners", output = "http://www.dat.eu/myClaim/soap/MyClaimExternalService/MyClaimExternalService/searchForPartnersResponse")
    public List<PartnerList> searchForPartners(
        @WebParam(name = "network", targetNamespace = "")
        NetworkType network,
        @WebParam(name = "rolePartner", targetNamespace = "")
        String rolePartner,
        @WebParam(name = "brandsSearchCriteria", targetNamespace = "")
        BrandSearch brandsSearchCriteria,
        @WebParam(name = "textSearchCriteria", targetNamespace = "")
        String textSearchCriteria,
        @WebParam(name = "location", targetNamespace = "")
        Location location,
        @WebParam(name = "distanceCalculationMode", targetNamespace = "")
        String distanceCalculationMode);

    /**
     * 
     * @param contractId
     * @param format
     * @param attributes
     * @param reportIdentification
     * @return
     *     returns de.dat.myclaim.soap.myclaimexternalservice.SoapFile
     */
    @WebMethod(action = "getPrintReport")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPrintReport", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.GetPrintReport")
    @ResponseWrapper(localName = "getPrintReportResponse", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.GetPrintReportResponse")
    @Action(input = "getPrintReport", output = "http://www.dat.eu/myClaim/soap/MyClaimExternalService/MyClaimExternalService/getPrintReportResponse")
    public SoapFile getPrintReport(
        @WebParam(name = "contractId", targetNamespace = "")
        long contractId,
        @WebParam(name = "reportIdentification", targetNamespace = "")
        String reportIdentification,
        @WebParam(name = "attributes", targetNamespace = "")
        Attributes attributes,
        @WebParam(name = "format", targetNamespace = "")
        String format);

    /**
     * 
     * @param invoiceRateId
     * @param contractId
     * @return
     *     returns boolean
     */
    @WebMethod(action = "assignInvoiceRateToContract")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "assignInvoiceRateToContract", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.AssignInvoiceRateToContract")
    @ResponseWrapper(localName = "assignInvoiceRateToContractResponse", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.AssignInvoiceRateToContractResponse")
    @Action(input = "assignInvoiceRateToContract", output = "http://www.dat.eu/myClaim/soap/MyClaimExternalService/MyClaimExternalService/assignInvoiceRateToContractResponse")
    public boolean assignInvoiceRateToContract(
        @WebParam(name = "contractId", targetNamespace = "")
        long contractId,
        @WebParam(name = "invoiceRateId", targetNamespace = "")
        long invoiceRateId);

    /**
     * 
     * @param brandName
     * @param partnerCustomerNumber
     * @param isoCountryCode
     * @param insuranceName
     * @param isFiType
     * @param network
     * @return
     *     returns de.dat.myclaim.soap.myclaimexternalservice.ListInvoiceRatesResponse.Return
     */
    @WebMethod(action = "listInvoiceRates")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listInvoiceRates", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.ListInvoiceRates")
    @ResponseWrapper(localName = "listInvoiceRatesResponse", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.ListInvoiceRatesResponse")
    @Action(input = "listInvoiceRates", output = "http://www.dat.eu/myClaim/soap/MyClaimExternalService/MyClaimExternalService/listInvoiceRatesResponse")
    public de.dat.myclaim.soap.myclaimexternalservice.ListInvoiceRatesResponse.Return listInvoiceRates(
        @WebParam(name = "isFiType", targetNamespace = "")
        boolean isFiType,
        @WebParam(name = "isoCountryCode", targetNamespace = "")
        String isoCountryCode,
        @WebParam(name = "network", targetNamespace = "")
        NetworkType network,
        @WebParam(name = "insuranceName", targetNamespace = "")
        String insuranceName,
        @WebParam(name = "brandName", targetNamespace = "")
        String brandName,
        @WebParam(name = "partnerCustomerNumber", targetNamespace = "")
        String partnerCustomerNumber);

    /**
     * 
     * @param tagIdentification
     * @param contractId
     * @param tagAddRemoveReplaceAction
     * @param networkType
     * @return
     *     returns int
     */
    @WebMethod(action = "setCustomTag")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setCustomTag", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.SetCustomTag")
    @ResponseWrapper(localName = "setCustomTagResponse", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.SetCustomTagResponse")
    @Action(input = "setCustomTag", output = "http://www.dat.eu/myClaim/soap/MyClaimExternalService/MyClaimExternalService/setCustomTagResponse")
    public int setCustomTag(
        @WebParam(name = "tagAddRemoveReplaceAction", targetNamespace = "")
        String tagAddRemoveReplaceAction,
        @WebParam(name = "tagIdentification", targetNamespace = "")
        String tagIdentification,
        @WebParam(name = "networkType", targetNamespace = "")
        String networkType,
        @WebParam(name = "contractId", targetNamespace = "")
        List<Long> contractId);

    /**
     * 
     * @param request
     * @return
     *     returns de.dat.myclaim.soap.myclaimexternalservice.InsuranceResponse
     */
    @WebMethod(action = "getInsurancesExt")
    @WebResult(name = "insurances", targetNamespace = "")
    @RequestWrapper(localName = "getInsurancesExt", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.GetInsurancesExt")
    @ResponseWrapper(localName = "getInsurancesExtResponse", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.GetInsurancesExtResponse")
    @Action(input = "getInsurancesExt", output = "http://www.dat.eu/myClaim/soap/MyClaimExternalService/MyClaimExternalService/getInsurancesExtResponse")
    public InsuranceResponse getInsurancesExt(
        @WebParam(name = "request", targetNamespace = "")
        InsurancesExtRequest request);

    /**
     * 
     * @param contractId
     * @return
     *     returns de.dat.myclaim.soap.myclaimexternalservice.MaterialPositions
     */
    @WebMethod(action = "getCalculatedSpareParts")
    @WebResult(name = "spareParts", targetNamespace = "http://www.dat.de/vxs")
    @RequestWrapper(localName = "getCalculatedSpareParts", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.GetCalculatedSpareParts")
    @ResponseWrapper(localName = "getCalculatedSparePartsResponse", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.GetCalculatedSparePartsResponse")
    @Action(input = "getCalculatedSpareParts", output = "http://www.dat.eu/myClaim/soap/MyClaimExternalService/MyClaimExternalService/getCalculatedSparePartsResponse")
    public MaterialPositions getCalculatedSpareParts(
        @WebParam(name = "contractId", targetNamespace = "")
        long contractId);

    /**
     * 
     * @param invoiceAttributes
     * @param summaryType
     * @param calculationSummary
     * @param contractId
     * @return
     *     returns java.lang.Long
     */
    @WebMethod(action = "importCalculationSummaryByType")
    @WebResult(name = "CalculationSummaryID", targetNamespace = "")
    @RequestWrapper(localName = "importCalculationSummaryByType", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.ImportCalculationSummaryByType")
    @ResponseWrapper(localName = "importCalculationSummaryByTypeResponse", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.ImportCalculationSummaryByTypeResponse")
    @Action(input = "importCalculationSummaryByType", output = "http://www.dat.eu/myClaim/soap/MyClaimExternalService/MyClaimExternalService/importCalculationSummaryByTypeResponse")
    public Long importCalculationSummaryByType(
        @WebParam(name = "contractId", targetNamespace = "")
        long contractId,
        @WebParam(name = "summaryType", targetNamespace = "")
        CalculationSummaryType summaryType,
        @WebParam(name = "CalculationSummary", targetNamespace = "http://www.dat.de/vxs")
        CalculationSummary calculationSummary,
        @WebParam(name = "invoiceAttributes", targetNamespace = "")
        InvoiceAttributes invoiceAttributes);

    /**
     * 
     * @param summaryType
     * @param contractId
     * @return
     *     returns de.dat.myclaim.soap.myclaimexternalservice.CalculationSummary
     */
    @WebMethod(action = "getCalculationSummaryByType")
    @WebResult(name = "CalculationSummary", targetNamespace = "http://www.dat.de/vxs")
    @RequestWrapper(localName = "getCalculationSummaryByType", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.GetCalculationSummaryByType")
    @ResponseWrapper(localName = "getCalculationSummaryByTypeResponse", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.GetCalculationSummaryByTypeResponse")
    @Action(input = "getCalculationSummaryByType", output = "http://www.dat.eu/myClaim/soap/MyClaimExternalService/MyClaimExternalService/getCalculationSummaryByTypeResponse")
    public CalculationSummary getCalculationSummaryByType(
        @WebParam(name = "contractId", targetNamespace = "")
        long contractId,
        @WebParam(name = "summaryType", targetNamespace = "")
        CalculationSummaryType summaryType);

    /**
     * 
     * @param networkType
     * @return
     *     returns java.util.List<de.dat.myclaim.soap.myclaimexternalservice.ContractStatus>
     */
    @WebMethod(action = "getPossibleNetworkStatuses")
    @WebResult(name = "PossibleNetworkStatuses", targetNamespace = "")
    @RequestWrapper(localName = "getPossibleNetworkStatuses", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.GetPossibleNetworkStatuses")
    @ResponseWrapper(localName = "getPossibleNetworkStatusesResponse", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.GetPossibleNetworkStatusesResponse")
    @Action(input = "getPossibleNetworkStatuses", output = "http://www.dat.eu/myClaim/soap/MyClaimExternalService/MyClaimExternalService/getPossibleNetworkStatusesResponse")
    public List<ContractStatus> getPossibleNetworkStatuses(
        @WebParam(name = "networkType", targetNamespace = "")
        String networkType);

    /**
     * 
     * @return
     *     returns java.util.List<de.dat.myclaim.soap.myclaimexternalservice.PossibleContactPersons>
     */
    @WebMethod(action = "getPossibleContactPersons")
    @WebResult(name = "PossibleContactPersons", targetNamespace = "")
    @RequestWrapper(localName = "getPossibleContactPersons", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.GetPossibleContactPersons")
    @ResponseWrapper(localName = "getPossibleContactPersonsResponse", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.GetPossibleContactPersonsResponse")
    @Action(input = "getPossibleContactPersons", output = "http://www.dat.eu/myClaim/soap/MyClaimExternalService/MyClaimExternalService/getPossibleContactPersonsResponse")
    public List<PossibleContactPersons> getPossibleContactPersons();

    /**
     * 
     * @param contractId
     * @return
     *     returns java.util.List<de.dat.myclaim.soap.myclaimexternalservice.ContractStatus>
     */
    @WebMethod(action = "getPossibleContractStatusTransitions")
    @WebResult(name = "PossibleContractStatusTransitions", targetNamespace = "")
    @RequestWrapper(localName = "getPossibleContractStatusTransitions", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.GetPossibleContractStatusTransitions")
    @ResponseWrapper(localName = "getPossibleContractStatusTransitionsResponse", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.GetPossibleContractStatusTransitionsResponse")
    @Action(input = "getPossibleContractStatusTransitions", output = "http://www.dat.eu/myClaim/soap/MyClaimExternalService/MyClaimExternalService/getPossibleContractStatusTransitionsResponse")
    public List<ContractStatus> getPossibleContractStatusTransitions(
        @WebParam(name = "contractId", targetNamespace = "")
        long contractId);

    /**
     * 
     * @param notificationsNewerThan
     * @param notificationTypes
     * @param claimsNewerThan
     * @return
     *     returns de.dat.myclaim.soap.myclaimexternalservice.NotificationsResponse
     */
    @WebMethod(action = "listNotifications")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listNotifications", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.ListNotifications")
    @ResponseWrapper(localName = "listNotificationsResponse", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.ListNotificationsResponse")
    @Action(input = "listNotifications", output = "http://www.dat.eu/myClaim/soap/MyClaimExternalService/MyClaimExternalService/listNotificationsResponse")
    public NotificationsResponse listNotifications(
        @WebParam(name = "claimsNewerThan", targetNamespace = "")
        XMLGregorianCalendar claimsNewerThan,
        @WebParam(name = "notificationsNewerThan", targetNamespace = "")
        XMLGregorianCalendar notificationsNewerThan,
        @WebParam(name = "notificationTypes", targetNamespace = "")
        List<NotificationType> notificationTypes);

    /**
     * 
     * @param id
     * @return
     *     returns de.dat.myclaim.soap.myclaimexternalservice.AddressBook
     */
    @WebMethod(action = "getAddressBook")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAddressBook", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.GetAddressBook")
    @ResponseWrapper(localName = "getAddressBookResponse", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.GetAddressBookResponse")
    @Action(input = "getAddressBook", output = "http://www.dat.eu/myClaim/soap/MyClaimExternalService/MyClaimExternalService/getAddressBookResponse")
    public AddressBook getAddressBook(
        @WebParam(name = "Id", targetNamespace = "")
        long id);

    /**
     * 
     * @param id
     */
    @WebMethod(action = "removeAddressBook")
    @RequestWrapper(localName = "removeAddressBook", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.RemoveAddressBook")
    @ResponseWrapper(localName = "removeAddressBookResponse", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.RemoveAddressBookResponse")
    @Action(input = "removeAddressBook", output = "http://www.dat.eu/myClaim/soap/MyClaimExternalService/MyClaimExternalService/removeAddressBookResponse")
    public void removeAddressBook(
        @WebParam(name = "Id", targetNamespace = "")
        long id);

    /**
     * 
     * @param filter
     * @param pageLimit
     * @param pageOffset
     * @return
     *     returns java.util.List<de.dat.myclaim.soap.myclaimexternalservice.AddressBook>
     */
    @WebMethod(action = "listAddressBook")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listAddressBook", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.ListAddressBook")
    @ResponseWrapper(localName = "listAddressBookResponse", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.ListAddressBookResponse")
    @Action(input = "listAddressBook", output = "http://www.dat.eu/myClaim/soap/MyClaimExternalService/MyClaimExternalService/listAddressBookResponse")
    public List<AddressBook> listAddressBook(
        @WebParam(name = "filter", targetNamespace = "")
        PossibleContactPersons filter,
        @WebParam(name = "pageLimit", targetNamespace = "")
        int pageLimit,
        @WebParam(name = "pageOffset", targetNamespace = "")
        int pageOffset);

    /**
     * 
     * @param addressBook
     * @return
     *     returns de.dat.myclaim.soap.myclaimexternalservice.AddressBook
     */
    @WebMethod(action = "saveAddressBook")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "saveAddressBook", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.SaveAddressBook")
    @ResponseWrapper(localName = "saveAddressBookResponse", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalService", className = "de.dat.myclaim.soap.myclaimexternalservice.SaveAddressBookResponse")
    @Action(input = "saveAddressBook", output = "http://www.dat.eu/myClaim/soap/MyClaimExternalService/MyClaimExternalService/saveAddressBookResponse")
    public AddressBook saveAddressBook(
        @WebParam(name = "addressBook", targetNamespace = "")
        AddressBook addressBook);

}
