
package de.dat.myclaim.soap.vehiclerepairservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "SecurityProblemException", targetNamespace = "http://www.dat.eu/myClaim/soap/v2/VehicleRepairService")
public class SecurityProblemException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private SecurityProblemException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public SecurityProblemException_Exception(String message, SecurityProblemException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public SecurityProblemException_Exception(String message, SecurityProblemException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: de.dat.myclaim.soap.vehiclerepairservice.SecurityProblemException
     */
    public SecurityProblemException getFaultInfo() {
        return faultInfo;
    }

}
