
package de.dat.partsinfo.spareparts;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SpareParts", targetNamespace = "http://sphinx.dat.de/services/SpareParts")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SpareParts {


    /**
     * 
     * @param request
     * @return
     *     returns de.dat.partsinfo.spareparts.SparePartResult
     */
    @WebMethod(action = "getModelInfoByMfrAndExtPartNo")
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getModelInfoByMfrAndExtPartNo", targetNamespace = "http://sphinx.dat.de/services/SpareParts", className = "de.dat.partsinfo.spareparts.GetModelInfoByMfrAndExtPartNo")
    @ResponseWrapper(localName = "getModelInfoByMfrAndExtPartNoResponse", targetNamespace = "http://sphinx.dat.de/services/SpareParts", className = "de.dat.partsinfo.spareparts.GetModelInfoByMfrAndExtPartNoResponse")
    @Action(input = "getModelInfoByMfrAndExtPartNo", output = "http://sphinx.dat.de/services/SpareParts/SpareParts/getModelInfoByMfrAndExtPartNoResponse")
    public SparePartResult getModelInfoByMfrAndExtPartNo(
        @WebParam(name = "request", targetNamespace = "")
        ModelInfoMfrAndExtPartNoRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns de.dat.partsinfo.spareparts.SparePartResult
     */
    @WebMethod(action = "getExtPartNoInfoByModelAndExtPartNo")
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getExtPartNoInfoByModelAndExtPartNo", targetNamespace = "http://sphinx.dat.de/services/SpareParts", className = "de.dat.partsinfo.spareparts.GetExtPartNoInfoByModelAndExtPartNo")
    @ResponseWrapper(localName = "getExtPartNoInfoByModelAndExtPartNoResponse", targetNamespace = "http://sphinx.dat.de/services/SpareParts", className = "de.dat.partsinfo.spareparts.GetExtPartNoInfoByModelAndExtPartNoResponse")
    @Action(input = "getExtPartNoInfoByModelAndExtPartNo", output = "http://sphinx.dat.de/services/SpareParts/SpareParts/getExtPartNoInfoByModelAndExtPartNoResponse")
    public SparePartResult getExtPartNoInfoByModelAndExtPartNo(
        @WebParam(name = "request", targetNamespace = "")
        ModelAndExtPartNoRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns de.dat.partsinfo.spareparts.SparePartResult
     */
    @WebMethod(action = "getExtPartNoInfoByFullVehicleAndIntPartNo")
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getExtPartNoInfoByFullVehicleAndIntPartNo", targetNamespace = "http://sphinx.dat.de/services/SpareParts", className = "de.dat.partsinfo.spareparts.GetExtPartNoInfoByFullVehicleAndIntPartNo")
    @ResponseWrapper(localName = "getExtPartNoInfoByFullVehicleAndIntPartNoResponse", targetNamespace = "http://sphinx.dat.de/services/SpareParts", className = "de.dat.partsinfo.spareparts.GetExtPartNoInfoByFullVehicleAndIntPartNoResponse")
    @Action(input = "getExtPartNoInfoByFullVehicleAndIntPartNo", output = "http://sphinx.dat.de/services/SpareParts/SpareParts/getExtPartNoInfoByFullVehicleAndIntPartNoResponse")
    public SparePartResult getExtPartNoInfoByFullVehicleAndIntPartNo(
        @WebParam(name = "request", targetNamespace = "")
        FullVehicleAndIntPartNoRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns de.dat.partsinfo.spareparts.SparePartResult
     */
    @WebMethod(action = "getExtPartNoInfoByMfrAndExtPartNo")
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getExtPartNoInfoByMfrAndExtPartNo", targetNamespace = "http://sphinx.dat.de/services/SpareParts", className = "de.dat.partsinfo.spareparts.GetExtPartNoInfoByMfrAndExtPartNo")
    @ResponseWrapper(localName = "getExtPartNoInfoByMfrAndExtPartNoResponse", targetNamespace = "http://sphinx.dat.de/services/SpareParts", className = "de.dat.partsinfo.spareparts.GetExtPartNoInfoByMfrAndExtPartNoResponse")
    @Action(input = "getExtPartNoInfoByMfrAndExtPartNo", output = "http://sphinx.dat.de/services/SpareParts/SpareParts/getExtPartNoInfoByMfrAndExtPartNoResponse")
    public SparePartResult getExtPartNoInfoByMfrAndExtPartNo(
        @WebParam(name = "request", targetNamespace = "")
        MfrAndExtPartNoRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns de.dat.partsinfo.spareparts.SparePartResult
     */
    @WebMethod(action = "getExtPartNoInfoByVinAndIntPartNo")
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getExtPartNoInfoByVinAndIntPartNo", targetNamespace = "http://sphinx.dat.de/services/SpareParts", className = "de.dat.partsinfo.spareparts.GetExtPartNoInfoByVinAndIntPartNo")
    @ResponseWrapper(localName = "getExtPartNoInfoByVinAndIntPartNoResponse", targetNamespace = "http://sphinx.dat.de/services/SpareParts", className = "de.dat.partsinfo.spareparts.GetExtPartNoInfoByVinAndIntPartNoResponse")
    @Action(input = "getExtPartNoInfoByVinAndIntPartNo", output = "http://sphinx.dat.de/services/SpareParts/SpareParts/getExtPartNoInfoByVinAndIntPartNoResponse")
    public SparePartResult getExtPartNoInfoByVinAndIntPartNo(
        @WebParam(name = "request", targetNamespace = "")
        VinAndIntPartNoRequest request);

}
