
package de.dat.myclaim.soap.myclaimexternalauthenticationservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MyClaimExternalAuthenticationService", targetNamespace = "http://www.dat.eu/myClaim/soap/MyClaimExternalAuthenticationService", wsdlLocation = "http://www.dat.de/myClaim/soap/MyClaimExternalAuthenticationService?wsdl")
public class MyClaimExternalAuthenticationService_Service
    extends Service
{

    private final static URL MYCLAIMEXTERNALAUTHENTICATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException MYCLAIMEXTERNALAUTHENTICATIONSERVICE_EXCEPTION;
    private final static QName MYCLAIMEXTERNALAUTHENTICATIONSERVICE_QNAME = new QName("http://www.dat.eu/myClaim/soap/MyClaimExternalAuthenticationService", "MyClaimExternalAuthenticationService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://www.dat.de/myClaim/soap/MyClaimExternalAuthenticationService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MYCLAIMEXTERNALAUTHENTICATIONSERVICE_WSDL_LOCATION = url;
        MYCLAIMEXTERNALAUTHENTICATIONSERVICE_EXCEPTION = e;
    }

    public MyClaimExternalAuthenticationService_Service() {
        super(__getWsdlLocation(), MYCLAIMEXTERNALAUTHENTICATIONSERVICE_QNAME);
    }

    public MyClaimExternalAuthenticationService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), MYCLAIMEXTERNALAUTHENTICATIONSERVICE_QNAME, features);
    }

    public MyClaimExternalAuthenticationService_Service(URL wsdlLocation) {
        super(wsdlLocation, MYCLAIMEXTERNALAUTHENTICATIONSERVICE_QNAME);
    }

    public MyClaimExternalAuthenticationService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MYCLAIMEXTERNALAUTHENTICATIONSERVICE_QNAME, features);
    }

    public MyClaimExternalAuthenticationService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MyClaimExternalAuthenticationService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MyClaimExternalAuthenticationService
     */
    @WebEndpoint(name = "MyClaimExternalAuthenticationServicePort")
    public MyClaimExternalAuthenticationService getMyClaimExternalAuthenticationServicePort() {
        return super.getPort(new QName("http://www.dat.eu/myClaim/soap/MyClaimExternalAuthenticationService", "MyClaimExternalAuthenticationServicePort"), MyClaimExternalAuthenticationService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MyClaimExternalAuthenticationService
     */
    @WebEndpoint(name = "MyClaimExternalAuthenticationServicePort")
    public MyClaimExternalAuthenticationService getMyClaimExternalAuthenticationServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.dat.eu/myClaim/soap/MyClaimExternalAuthenticationService", "MyClaimExternalAuthenticationServicePort"), MyClaimExternalAuthenticationService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MYCLAIMEXTERNALAUTHENTICATIONSERVICE_EXCEPTION!= null) {
            throw MYCLAIMEXTERNALAUTHENTICATIONSERVICE_EXCEPTION;
        }
        return MYCLAIMEXTERNALAUTHENTICATIONSERVICE_WSDL_LOCATION;
    }

}
