
package de.dat.vehiclerepaironline.services.dossier;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DossierWebService", targetNamespace = "http://sphinx.dat.de/services/DossierWebService")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DossierWebService {


    /**
     * 
     * @param coverage
     * @param dossierId
     * @return
     *     returns de.dat.vehiclerepaironline.services.dossier.Dossiers
     */
    @WebMethod(action = "getDossier")
    @WebResult(name = "Dossiers", targetNamespace = "http://www.dat.de/vxs")
    @RequestWrapper(localName = "getDossier", targetNamespace = "http://sphinx.dat.de/services/DossierWebService", className = "de.dat.vehiclerepaironline.services.dossier.GetDossier")
    @ResponseWrapper(localName = "getDossierResponse", targetNamespace = "http://sphinx.dat.de/services/DossierWebService", className = "de.dat.vehiclerepaironline.services.dossier.GetDossierResponse")
    @Action(input = "getDossier", output = "http://sphinx.dat.de/services/DossierWebService/DossierWebService/getDossierResponse")
    public Dossiers getDossier(
        @WebParam(name = "DossierId", targetNamespace = "")
        Long dossierId,
        @WebParam(name = "Coverage", targetNamespace = "")
        String coverage);

    /**
     * 
     * @param dossiers
     * @return
     *     returns java.lang.Long
     */
    @WebMethod(action = "changeDossier")
    @WebResult(name = "contract", targetNamespace = "")
    @RequestWrapper(localName = "changeDossier", targetNamespace = "http://sphinx.dat.de/services/DossierWebService", className = "de.dat.vehiclerepaironline.services.dossier.ChangeDossier")
    @ResponseWrapper(localName = "changeDossierResponse", targetNamespace = "http://sphinx.dat.de/services/DossierWebService", className = "de.dat.vehiclerepaironline.services.dossier.ChangeDossierResponse")
    @Action(input = "changeDossier", output = "http://sphinx.dat.de/services/DossierWebService/DossierWebService/changeDossierResponse")
    public Long changeDossier(
        @WebParam(name = "Dossiers", targetNamespace = "http://www.dat.de/vxs")
        Dossiers dossiers);

    /**
     * 
     * @param dossiers
     * @return
     *     returns java.lang.Long
     */
    @WebMethod(action = "createDossier")
    @WebResult(name = "contract", targetNamespace = "")
    @RequestWrapper(localName = "createDossier", targetNamespace = "http://sphinx.dat.de/services/DossierWebService", className = "de.dat.vehiclerepaironline.services.dossier.CreateDossier")
    @ResponseWrapper(localName = "createDossierResponse", targetNamespace = "http://sphinx.dat.de/services/DossierWebService", className = "de.dat.vehiclerepaironline.services.dossier.CreateDossierResponse")
    @Action(input = "createDossier", output = "http://sphinx.dat.de/services/DossierWebService/DossierWebService/createDossierResponse")
    public Long createDossier(
        @WebParam(name = "Dossiers", targetNamespace = "http://www.dat.de/vxs")
        Dossiers dossiers);

    /**
     * 
     * @param dossierId
     * @return
     *     returns boolean
     */
    @WebMethod(action = "deleteDossier")
    @WebResult(name = "success", targetNamespace = "http://www.dat.de/vxs")
    @RequestWrapper(localName = "deleteDossier", targetNamespace = "http://sphinx.dat.de/services/DossierWebService", className = "de.dat.vehiclerepaironline.services.dossier.DeleteDossier")
    @ResponseWrapper(localName = "deleteDossierResponse", targetNamespace = "http://sphinx.dat.de/services/DossierWebService", className = "de.dat.vehiclerepaironline.services.dossier.DeleteDossierResponse")
    @Action(input = "deleteDossier", output = "http://sphinx.dat.de/services/DossierWebService/DossierWebService/deleteDossierResponse")
    public boolean deleteDossier(
        @WebParam(name = "DossierId", targetNamespace = "")
        Long dossierId);

}
