
package de.dat.vehiclerepaironline.services.dossier;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Dossier", targetNamespace = "http://sphinx.dat.de/services/DossierWebService", wsdlLocation = "http://www.dat.de/VehicleRepairOnline/services/Dossier?wsdl")
public class Dossier_Service
    extends Service
{

    private final static URL DOSSIER_WSDL_LOCATION;
    private final static WebServiceException DOSSIER_EXCEPTION;
    private final static QName DOSSIER_QNAME = new QName("http://sphinx.dat.de/services/DossierWebService", "Dossier");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://www.dat.de/VehicleRepairOnline/services/Dossier?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DOSSIER_WSDL_LOCATION = url;
        DOSSIER_EXCEPTION = e;
    }

    public Dossier_Service() {
        super(__getWsdlLocation(), DOSSIER_QNAME);
    }

    public Dossier_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), DOSSIER_QNAME, features);
    }

    public Dossier_Service(URL wsdlLocation) {
        super(wsdlLocation, DOSSIER_QNAME);
    }

    public Dossier_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DOSSIER_QNAME, features);
    }

    public Dossier_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Dossier_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DossierWebService
     */
    @WebEndpoint(name = "DossierPort")
    public DossierWebService getDossierPort() {
        return super.getPort(new QName("http://sphinx.dat.de/services/DossierWebService", "DossierPort"), DossierWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DossierWebService
     */
    @WebEndpoint(name = "DossierPort")
    public DossierWebService getDossierPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://sphinx.dat.de/services/DossierWebService", "DossierPort"), DossierWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DOSSIER_EXCEPTION!= null) {
            throw DOSSIER_EXCEPTION;
        }
        return DOSSIER_WSDL_LOCATION;
    }

}
