
package de.dat.datecodeselection.services.conversionfunctionsservice;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ConversionFunctionsService", targetNamespace = "http://sphinx.dat.de/services/ConversionFunctionsService")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ConversionFunctionsService {


    /**
     * 
     * @param request
     * @return
     *     returns de.dat.datecodeselection.services.conversionfunctionsservice.VXS
     */
    @WebMethod(action = "getEquipmentFromManufacturerCodeN")
    @WebResult(name = "VXS", targetNamespace = "http://www.dat.de/vxs")
    @RequestWrapper(localName = "getEquipmentFromManufacturerCodeN", targetNamespace = "http://sphinx.dat.de/services/ConversionFunctionsService", className = "de.dat.datecodeselection.services.conversionfunctionsservice.GetEquipmentFromManufacturerCodeN")
    @ResponseWrapper(localName = "getEquipmentFromManufacturerCodeNResponse", targetNamespace = "http://sphinx.dat.de/services/ConversionFunctionsService", className = "de.dat.datecodeselection.services.conversionfunctionsservice.GetEquipmentFromManufacturerCodeNResponse")
    @Action(input = "getEquipmentFromManufacturerCodeN", output = "http://sphinx.dat.de/services/ConversionFunctionsService/ConversionFunctionsService/getEquipmentFromManufacturerCodeNResponse")
    public VXS getEquipmentFromManufacturerCodeN(
        @WebParam(name = "request", targetNamespace = "")
        EquipmentFromManufacturerCodeSelectionRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns java.lang.Object
     */
    @WebMethod(action = "constructionTime2Date")
    @WebResult(name = "Date", targetNamespace = "")
    @RequestWrapper(localName = "constructionTime2Date", targetNamespace = "http://sphinx.dat.de/services/ConversionFunctionsService", className = "de.dat.datecodeselection.services.conversionfunctionsservice.ConstructionTime2Date")
    @ResponseWrapper(localName = "constructionTime2DateResponse", targetNamespace = "http://sphinx.dat.de/services/ConversionFunctionsService", className = "de.dat.datecodeselection.services.conversionfunctionsservice.ConstructionTime2DateResponse")
    @Action(input = "constructionTime2Date", output = "http://sphinx.dat.de/services/ConversionFunctionsService/ConversionFunctionsService/constructionTime2DateResponse")
    public Object constructionTime2Date(
        @WebParam(name = "request", targetNamespace = "")
        ConstructionTime2DateSelectionRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns int
     */
    @WebMethod(action = "date2ConstructionTime")
    @WebResult(name = "constructionTime", targetNamespace = "")
    @RequestWrapper(localName = "date2ConstructionTime", targetNamespace = "http://sphinx.dat.de/services/ConversionFunctionsService", className = "de.dat.datecodeselection.services.conversionfunctionsservice.Date2ConstructionTime")
    @ResponseWrapper(localName = "date2ConstructionTimeResponse", targetNamespace = "http://sphinx.dat.de/services/ConversionFunctionsService", className = "de.dat.datecodeselection.services.conversionfunctionsservice.Date2ConstructionTimeResponse")
    @Action(input = "date2ConstructionTime", output = "http://sphinx.dat.de/services/ConversionFunctionsService/ConversionFunctionsService/date2ConstructionTimeResponse")
    public int date2ConstructionTime(
        @WebParam(name = "request", targetNamespace = "")
        Date2ConstructionTimeSelectionRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns de.dat.datecodeselection.services.conversionfunctionsservice.ValueCodeDescription
     */
    @WebMethod(action = "valueCode2Description")
    @WebResult(name = "valueCodeDescription", targetNamespace = "")
    @RequestWrapper(localName = "valueCode2Description", targetNamespace = "http://sphinx.dat.de/services/ConversionFunctionsService", className = "de.dat.datecodeselection.services.conversionfunctionsservice.ValueCode2Description")
    @ResponseWrapper(localName = "valueCode2DescriptionResponse", targetNamespace = "http://sphinx.dat.de/services/ConversionFunctionsService", className = "de.dat.datecodeselection.services.conversionfunctionsservice.ValueCode2DescriptionResponse")
    @Action(input = "valueCode2Description", output = "http://sphinx.dat.de/services/ConversionFunctionsService/ConversionFunctionsService/valueCode2DescriptionResponse")
    public ValueCodeDescription valueCode2Description(
        @WebParam(name = "request", targetNamespace = "")
        ConstructionPeriodSelectionRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns de.dat.datecodeselection.services.conversionfunctionsservice.VXS
     */
    @WebMethod(action = "getExistingEquipmentN")
    @WebResult(name = "VXS", targetNamespace = "http://www.dat.de/vxs")
    @RequestWrapper(localName = "getExistingEquipmentN", targetNamespace = "http://sphinx.dat.de/services/ConversionFunctionsService", className = "de.dat.datecodeselection.services.conversionfunctionsservice.GetExistingEquipmentN")
    @ResponseWrapper(localName = "getExistingEquipmentNResponse", targetNamespace = "http://sphinx.dat.de/services/ConversionFunctionsService", className = "de.dat.datecodeselection.services.conversionfunctionsservice.GetExistingEquipmentNResponse")
    @Action(input = "getExistingEquipmentN", output = "http://sphinx.dat.de/services/ConversionFunctionsService/ConversionFunctionsService/getExistingEquipmentNResponse")
    public VXS getExistingEquipmentN(
        @WebParam(name = "request", targetNamespace = "")
        VehicleSelectionRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns de.dat.datecodeselection.services.conversionfunctionsservice.VXS
     */
    @WebMethod(action = "getPossibleEquipmentN")
    @WebResult(name = "VXS", targetNamespace = "http://www.dat.de/vxs")
    @RequestWrapper(localName = "getPossibleEquipmentN", targetNamespace = "http://sphinx.dat.de/services/ConversionFunctionsService", className = "de.dat.datecodeselection.services.conversionfunctionsservice.GetPossibleEquipmentN")
    @ResponseWrapper(localName = "getPossibleEquipmentNResponse", targetNamespace = "http://sphinx.dat.de/services/ConversionFunctionsService", className = "de.dat.datecodeselection.services.conversionfunctionsservice.GetPossibleEquipmentNResponse")
    @Action(input = "getPossibleEquipmentN", output = "http://sphinx.dat.de/services/ConversionFunctionsService/ConversionFunctionsService/getPossibleEquipmentNResponse")
    public VXS getPossibleEquipmentN(
        @WebParam(name = "request", targetNamespace = "")
        VehicleSelectionRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns java.util.List<de.dat.datecodeselection.services.conversionfunctionsservice.StringStringPair>
     */
    @WebMethod(action = "getEquipmentGroups")
    @WebResult(name = "equipmentGroup", targetNamespace = "")
    @RequestWrapper(localName = "getEquipmentGroups", targetNamespace = "http://sphinx.dat.de/services/ConversionFunctionsService", className = "de.dat.datecodeselection.services.conversionfunctionsservice.GetEquipmentGroups")
    @ResponseWrapper(localName = "getEquipmentGroupsResponse", targetNamespace = "http://sphinx.dat.de/services/ConversionFunctionsService", className = "de.dat.datecodeselection.services.conversionfunctionsservice.GetEquipmentGroupsResponse")
    @Action(input = "getEquipmentGroups", output = "http://sphinx.dat.de/services/ConversionFunctionsService/ConversionFunctionsService/getEquipmentGroupsResponse")
    public List<StringStringPair> getEquipmentGroups(
        @WebParam(name = "request", targetNamespace = "")
        AbstractSelectionRequest request);

}
