
package de.dat.vehiclerepaironline.dossierservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DossierService", targetNamespace = "http://sphinx.dat.de/services/DossierWebService", wsdlLocation = "http://www.dat.de/VehicleRepairOnline/services/DossierService?wsdl")
public class DossierService
    extends Service
{

    private final static URL DOSSIERSERVICE_WSDL_LOCATION;
    private final static WebServiceException DOSSIERSERVICE_EXCEPTION;
    private final static QName DOSSIERSERVICE_QNAME = new QName("http://sphinx.dat.de/services/DossierWebService", "DossierService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://www.dat.de/VehicleRepairOnline/services/DossierService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DOSSIERSERVICE_WSDL_LOCATION = url;
        DOSSIERSERVICE_EXCEPTION = e;
    }

    public DossierService() {
        super(__getWsdlLocation(), DOSSIERSERVICE_QNAME);
    }

    public DossierService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DOSSIERSERVICE_QNAME, features);
    }

    public DossierService(URL wsdlLocation) {
        super(wsdlLocation, DOSSIERSERVICE_QNAME);
    }

    public DossierService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DOSSIERSERVICE_QNAME, features);
    }

    public DossierService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DossierService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DossierWebService
     */
    @WebEndpoint(name = "DossierServicePort")
    public DossierWebService getDossierServicePort() {
        return super.getPort(new QName("http://sphinx.dat.de/services/DossierWebService", "DossierServicePort"), DossierWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DossierWebService
     */
    @WebEndpoint(name = "DossierServicePort")
    public DossierWebService getDossierServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://sphinx.dat.de/services/DossierWebService", "DossierServicePort"), DossierWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DOSSIERSERVICE_EXCEPTION!= null) {
            throw DOSSIERSERVICE_EXCEPTION;
        }
        return DOSSIERSERVICE_WSDL_LOCATION;
    }

}
